import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

function readAppShellSource(relativePath: string): string {
  return readFileSync(
    resolve(process.cwd(), "apps", "demo-frontend", "app-shell", "src", ...relativePath.split("/")),
    "utf8",
  );
}

function readRepoSource(relativePath: string): string {
  return readFileSync(resolve(process.cwd(), ...relativePath.split("/")), "utf8");
}

test("app shell wraps routes with the workspace runtime provider", () => {
  const source = readAppShellSource("App.tsx");

  assert.match(source, /import \{ WorkspaceRuntimeProvider \} from "@\/hooks\/useWorkspaceRuntime";/);
  assert.match(source, /<WorkspaceRuntimeProvider>/);
  assert.match(source, /<\/WorkspaceRuntimeProvider>/);
  assert.match(source, /<Route path="\/app\/console\/runtime" element=\{<ConsoleRuntime \/>} \/>/);
});

test("live desk and console surfaces prefer repo-owned runtime data with draft fallback support", () => {
  const liveDesk = readAppShellSource("components/workspace/LiveDesk.tsx");
  const consoleStage = readAppShellSource("components/workspace/ConsoleStage.tsx");
  const consoleRuntime = readAppShellSource("pages/ConsoleRuntime.tsx");
  const caseWikiPanel = readAppShellSource("components/workspace/CaseWikiPanel.tsx");
  const caseVaultPanel = readAppShellSource("components/workspace/CaseVaultPanel.tsx");
  const runtimeDiagnosticsPanels = readAppShellSource("components/workspace/RuntimeDiagnosticsPanels.tsx");
  const sessionBoundaryPanel = readAppShellSource("components/workspace/SessionBoundaryPanel.tsx");
  const sessionOpsPanel = readAppShellSource("components/workspace/SessionOpsPanel.tsx");
  const artifactViewerPanel = readAppShellSource("components/workspace/ArtifactViewerPanel.tsx");
  const artifactViewerLib = readAppShellSource("lib/runtime-artifact-viewer.ts");
  const replayRuntime = readAppShellSource("lib/runtime-session-replay.ts");
  const workspaceRuntime = readAppShellSource("hooks/useWorkspaceRuntime.tsx");
  const consolePage = readAppShellSource("pages/Console.tsx");
  const bundlePage = readAppShellSource("pages/Bundle.tsx");
  const evidenceDetailPage = readAppShellSource("pages/EvidenceDetail.tsx");

  assert.match(liveDesk, /const \{ cases, deviceNodes, addDraftCase, getCaseWikiByRef \} = useWorkspaceRuntime\(\);/);
  assert.match(liveDesk, /existingCases=\{cases\}/);
  assert.match(liveDesk, /addDraftCase\(draft\);/);
  assert.match(liveDesk, /const activePlaybookWiki = useMemo/);
  assert.match(liveDesk, /deviceNodes\.find\(\(n\) => n\.id === nodeFilterId\)/);
  assert.match(liveDesk, /buildCaseVaultPath/);
  assert.match(liveDesk, /Open Case Vault/);
  assert.match(liveDesk, /handleOpenCaseVault/);

  assert.match(consoleStage, /const \{ deviceNodes, getCaseByRef, getCaseWikiByRef \} = useWorkspaceRuntime\(\);/);
  assert.match(consoleStage, /const baseCase = getCaseByRef\(caseRef\);/);
  assert.match(consoleStage, /deviceNodes\.find\(\(n\) => n\.id === c\.sourceNodeId\)/);
  assert.match(consoleStage, /buildCaseVaultPath/);
  assert.match(consoleStage, /buildCaseRuntimeSupportPath/);
  assert.match(consoleStage, /handleOpenCaseVault/);
  assert.match(consoleStage, /label="Open Case Vault"/);
  assert.match(consoleStage, /Runtime support/);
  assert.match(consoleStage, /const showRuntimeSupportStrip = runtimeSupportItems\.length > 0;/);
  assert.match(consoleStage, /if \(exportReady !== true\)/);
  assert.match(consoleStage, /if \(!proofPublished\)/);
  assert.match(consoleStage, /if \(replayNeedsAttention\)/);
  assert.match(consoleStage, /const runtimeSupportCta = exportReady !== true/);
  assert.match(consoleStage, /Inspect compliance blocker/);
  assert.match(consoleStage, /Inspect raw artifact blocker/);
  assert.match(consoleStage, /Inspect signature pending/);
  assert.match(consoleStage, /Inspect unsigned proof/);
  assert.match(consoleStage, /const signatureStatus = wiki\?\.evidenceSignature\?\.status \?\? null;/);
  assert.match(consoleStage, /const compliancePrimaryAction = complianceRemediation\?\.primaryAction \?\? null;/);
  assert.match(consoleStage, /const hasRawArtifactBlocker =/);
  assert.match(consoleStage, /const hasSignatureBlocker =/);
  assert.match(consoleStage, /function formatRuntimeSupportRef/);
  assert.match(consoleStage, /const runtimeSupportHint = exportReady !== true/);
  assert.match(consoleStage, /operatorActionLabel/);
  assert.match(consoleStage, /blockingRef/);
  assert.match(consoleStage, /id="action-queue"/);
  assert.match(consoleStage, /id="live-activity"/);
  assert.doesNotMatch(consoleStage, /SessionBoundaryPanel/);
  assert.doesNotMatch(consoleStage, /CaseWikiPanel/);
  assert.doesNotMatch(consoleStage, /SessionOpsPanel/);
  assert.doesNotMatch(consoleStage, /RuntimeDiagnosticsPanels/);
  assert.match(consoleRuntime, /const \{ defaultConsoleCaseRef, getCaseByRef, getCaseWikiByRef \} = useWorkspaceRuntime\(\);/);
  assert.match(consoleRuntime, /<Topbar section="Operator Runtime" caseRef=\{caseRef\} \/>/);
  assert.match(consoleRuntime, /<SessionBoundaryPanel caseValue=\{runtimeCase\} wiki=\{wiki\} \/>/);
  assert.match(consoleRuntime, /<CaseWikiPanel caseValue=\{runtimeCase\} wiki=\{wiki\} \/>/);
  assert.match(consoleRuntime, /<CaseVaultPanel caseValue=\{runtimeCase\} wiki=\{wiki\} \/>/);
  assert.match(consoleRuntime, /<SessionOpsPanel caseValue=\{runtimeCase\} wiki=\{wiki\} \/>/);
  assert.match(consoleRuntime, /<RuntimeDiagnosticsPanels caseValue=\{runtimeCase\} wiki=\{wiki\} \/>/);
  assert.match(consoleRuntime, /const initialArtifactPath = params\.get\("artifact"\);/);
  assert.match(consoleRuntime, /const initialArtifactIssue = params\.get\("issue"\);/);
  assert.match(consoleRuntime, /const initialArtifactSection = params\.get\("section"\);/);
  assert.match(consoleRuntime, /const initialFocusedOnly = params\.get\("focusedOnly"\) === "1";/);
  assert.match(consoleRuntime, /const handleFocusedOnlyChange = \(enabled: boolean\) => \{/);
  assert.match(consoleRuntime, /const nextParams = new URLSearchParams\(params\);/);
  assert.match(consoleRuntime, /nextParams\.set\("focusedOnly", "1"\);/);
  assert.match(consoleRuntime, /nextParams\.delete\("focusedOnly"\);/);
  assert.match(consoleRuntime, /<ArtifactViewerPanel[\s\S]*initialArtifactPath=\{initialArtifactPath\}[\s\S]*initialArtifactIssue=\{initialArtifactIssue\}[\s\S]*initialArtifactSection=\{initialArtifactSection\}[\s\S]*initialCaseRef=\{runtimeCase\.ref\}[\s\S]*initialFocusedOnly=\{initialFocusedOnly\}[\s\S]*onFocusedOnlyChange=\{handleFocusedOnlyChange\}[\s\S]*\/>/);
  assert.match(consoleRuntime, /navigate\(`\/app\/console\$\{search \? `\?\$\{search\}` : ""\}\$\{hash\}`/);
  assert.match(caseWikiPanel, /Copy handoff/);
  assert.match(caseWikiPanel, /Copy refs/);
  assert.match(caseWikiPanel, /Open bundle/);
  assert.match(caseWikiPanel, /Open evidence/);
  assert.match(caseWikiPanel, /Inspect proof/);
  assert.match(caseWikiPanel, /Open Case Vault/);
  assert.match(caseWikiPanel, /id="case-wiki"/);
  assert.match(caseWikiPanel, /buildCaseVaultPath/);
  assert.match(caseWikiPanel, /buildRuntimeArtifactViewerPath/);
  assert.match(caseWikiPanel, /buildRuntimeArtifactIssueViewerPath/);
  assert.match(caseWikiPanel, /RUNTIME_ARTIFACT_VIEW_PRESETS\.runtimeProof/);
  assert.match(caseWikiPanel, /exportReady === false/);
  assert.match(caseWikiPanel, /operatorPreviewPack\?\.remediation\?\.draft/);
  assert.match(caseWikiPanel, /compliance\?\.enforcement\?\.summary/);
  assert.match(caseWikiPanel, /evidenceSignature\?\.status/);
  assert.match(caseWikiPanel, /const remediationPrimaryAction = complianceEnforcement\?\.remediation\?\.primaryAction \?\? null;/);
  assert.match(caseWikiPanel, /const remediationHint = \[/);
  assert.match(caseWikiPanel, /formatRemediationRef/);
  assert.match(caseWikiPanel, /Raw artifact blocker/);
  assert.match(caseWikiPanel, /Signature pending/);
  assert.match(caseWikiPanel, /Next repo-owned step:/);
  assert.match(caseWikiPanel, /Inspect blocker evidence/);
  assert.match(caseWikiPanel, /Inspect signature evidence/);
  assert.match(caseWikiPanel, /Inspect export evidence/);
  assert.match(caseWikiPanel, /Inspect proof evidence/);
  assert.match(workspaceRuntime, /blockingReasons\?: string\[\] \| null;/);
  assert.match(workspaceRuntime, /primaryAction\?: \{/);
  assert.match(caseVaultPanel, /id="case-vault"/);
  assert.match(caseVaultPanel, /Inspectable memory projection/);
  assert.match(caseVaultPanel, /Rowboat-style/);
  assert.match(caseVaultPanel, /Memory anchors/);
  assert.match(caseVaultPanel, /Open threads/);
  assert.match(caseVaultPanel, /Evidence map/);
  assert.match(caseVaultPanel, /Linked entities/);
  assert.match(caseVaultPanel, /Recent memory trail/);
  assert.match(caseVaultPanel, /Operator handoff/);
  assert.match(caseVaultPanel, /CRM prep/);
  assert.match(caseVaultPanel, /Operator handoff projection/);
  assert.match(caseVaultPanel, /CRM prep projection/);
  assert.match(caseVaultPanel, /Copy memory/);
  assert.match(caseVaultPanel, /Copy handoff/);
  assert.match(caseVaultPanel, /Copy CRM prep/);
  assert.match(caseVaultPanel, /Export Markdown/);
  assert.match(caseVaultPanel, /Export CRM Markdown/);
  assert.match(caseVaultPanel, /Open bundle/);
  assert.match(caseVaultPanel, /Open evidence/);
  assert.match(caseVaultPanel, /Case Vault handoff ready/);
  assert.match(caseVaultPanel, /Case Vault export blocked/);
  assert.match(caseVaultPanel, /Case Vault CRM prep ready/);
  assert.match(caseVaultPanel, /Case Vault CRM prep blocked/);
  assert.match(caseVaultPanel, /Inspect proof/);
  assert.match(caseVaultPanel, /buildRuntimeArtifactIssueViewerPath/);
  assert.match(caseVaultPanel, /const remediationPrimaryAction = complianceEnforcement\?\.remediation\?\.primaryAction \?\? null;/);
  assert.match(caseVaultPanel, /const remediationHint = \[/);
  assert.match(caseVaultPanel, /formatRemediationRef/);
  assert.match(caseVaultPanel, /Raw artifact blocker/);
  assert.match(caseVaultPanel, /Signature pending/);
  assert.match(caseVaultPanel, /Next repo-owned step:/);
  assert.match(caseVaultPanel, /Inspect blocker evidence/);
  assert.match(caseVaultPanel, /Inspect signature evidence/);
  assert.match(caseVaultPanel, /Inspect export evidence/);
  assert.match(caseVaultPanel, /Inspect export posture/);
  assert.match(sessionBoundaryPanel, /Session Boundary/);
  assert.match(sessionBoundaryPanel, /id="connections"/);
  assert.match(sessionBoundaryPanel, /fetchRuntimeSessionReplay/);
  assert.match(sessionBoundaryPanel, /buildRuntimeSessionReplaySummary/);
  assert.match(sessionBoundaryPanel, /buildRuntimeArtifactViewerPath/);
  assert.match(sessionBoundaryPanel, /RUNTIME_ARTIFACT_VIEW_PRESETS\.runtimeProof/);
  assert.match(sessionBoundaryPanel, /Inspect proof/);
  assert.match(sessionBoundaryPanel, /Proof ingress:/);
  assert.match(sessionBoundaryPanel, /Turn ingress:/);
  assert.match(sessionBoundaryPanel, /After refresh/);
  assert.match(sessionOpsPanel, /Operator Session Ops/);
  assert.match(sessionOpsPanel, /id="session-ops"/);
  assert.match(sessionOpsPanel, /Export Markdown/);
  assert.match(sessionOpsPanel, /Export JSON/);
  assert.match(sessionOpsPanel, /Refresh replay/);
  assert.match(sessionOpsPanel, /Refresh Case Wiki/);
  assert.match(sessionOpsPanel, /buildRuntimeArtifactViewerPath/);
  assert.match(sessionOpsPanel, /buildRuntimeArtifactIssueViewerPath/);
  assert.match(sessionOpsPanel, /RUNTIME_ARTIFACT_VIEW_PRESETS\.manifest/);
  assert.match(sessionOpsPanel, /Inspect manifest/);
  assert.match(sessionOpsPanel, /buildSessionExportPayload/);
  assert.match(sessionOpsPanel, /buildSessionExportMarkdown/);
  assert.match(sessionOpsPanel, /case wiki export blocked/);
  assert.match(sessionOpsPanel, /const remediationPrimaryAction = complianceEnforcement\?\.remediation\?\.primaryAction \?\? null;/);
  assert.match(sessionOpsPanel, /const remediationHint = \[/);
  assert.match(sessionOpsPanel, /formatRemediationRef/);
  assert.match(sessionOpsPanel, /Raw artifact blocker/);
  assert.match(sessionOpsPanel, /Signature pending/);
  assert.match(sessionOpsPanel, /Next repo-owned step:/);
  assert.match(sessionOpsPanel, /Inspect blocker evidence/);
  assert.match(sessionOpsPanel, /Inspect signature evidence/);
  assert.match(sessionOpsPanel, /Inspect export evidence/);
  assert.match(sessionOpsPanel, /Inspect export posture/);
  assert.match(replayRuntime, /export async function fetchRuntimeSessionReplay/);
  assert.match(replayRuntime, /export function buildRuntimeSessionReplaySummary/);
  assert.match(replayRuntime, /export function buildSessionExportPayload/);
  assert.match(replayRuntime, /export function buildSessionExportMarkdown/);
  assert.match(replayRuntime, /latestProofIngressSource/);
  assert.match(replayRuntime, /primaryStepRefreshFollowupPath/);
  assert.match(runtimeDiagnosticsPanels, /Workflow Runtime/);
  assert.match(runtimeDiagnosticsPanels, /Runtime Guardrails/);
  assert.match(runtimeDiagnosticsPanels, /Bootstrap Doctor/);
  assert.match(runtimeDiagnosticsPanels, /Browser Workers/);
  assert.match(runtimeDiagnosticsPanels, /id="safety-rules"/);
  assert.match(runtimeDiagnosticsPanels, /id="health-check"/);
  assert.match(runtimeDiagnosticsPanels, /readJsonDataRecord\(\s*"\/v1\/runtime\/workflow-config"/);
  assert.match(runtimeDiagnosticsPanels, /readJsonDataRecord\(\s*"\/v1\/runtime\/workflow-control-plane-override"/);
  assert.match(runtimeDiagnosticsPanels, /readJsonDataRecord\(\s*"\/v1\/runtime\/bootstrap-status"/);
  assert.match(runtimeDiagnosticsPanels, /fetchRuntimeApi\(\s*"\/v1\/runtime\/auth-profiles"/);
  assert.match(runtimeDiagnosticsPanels, /fetchRuntimeApi\(\s*"\/v1\/runtime\/auth-profiles\/rotate"/);
  assert.match(runtimeDiagnosticsPanels, /readJsonDataRecord\(\s*"\/v1\/runtime\/browser-jobs\?limit=6"/);
  assert.match(runtimeDiagnosticsPanels, /buildRuntimeArtifactViewerPath/);
  assert.match(runtimeDiagnosticsPanels, /buildRuntimeArtifactIssueViewerPath/);
  assert.match(runtimeDiagnosticsPanels, /RUNTIME_ARTIFACT_VIEW_PRESETS\.report/);
  assert.match(runtimeDiagnosticsPanels, /RUNTIME_ARTIFACT_VIEW_PRESETS\.badgeDetails/);
  assert.match(runtimeDiagnosticsPanels, /Refresh workflow/);
  assert.match(runtimeDiagnosticsPanels, /Inspect report/);
  assert.match(runtimeDiagnosticsPanels, /Clear override/);
  assert.match(runtimeDiagnosticsPanels, /Refresh guardrails/);
  assert.match(runtimeDiagnosticsPanels, /Inspect badge/);
  assert.match(runtimeDiagnosticsPanels, /type RuntimeDiagnosticsPanelsProps = \{\s*caseValue: WorkspaceCase;\s*wiki: RuntimeCaseWiki \| undefined;/);
  assert.match(runtimeDiagnosticsPanels, /const remediationPrimaryAction = complianceEnforcement\?\.remediation\?\.primaryAction \?\? null;/);
  assert.match(runtimeDiagnosticsPanels, /formatRemediationRef/);
  assert.match(runtimeDiagnosticsPanels, /Raw artifact blocker/);
  assert.match(runtimeDiagnosticsPanels, /Signature pending/);
  assert.match(runtimeDiagnosticsPanels, /Next repo-owned step:/);
  assert.match(runtimeDiagnosticsPanels, /Inspect blocker evidence/);
  assert.match(runtimeDiagnosticsPanels, /Inspect signature evidence/);
  assert.match(runtimeDiagnosticsPanels, /Inspect export evidence/);
  assert.match(runtimeDiagnosticsPanels, /Workflow Runtime/);
  assert.match(runtimeDiagnosticsPanels, /Refresh doctor/);
  assert.match(runtimeDiagnosticsPanels, /Rotate next credential/);
  assert.match(runtimeDiagnosticsPanels, /Refresh workers/);
  assert.match(runtimeDiagnosticsPanels, /Resume job/);
  assert.match(runtimeDiagnosticsPanels, /Cancel job/);
  assert.match(artifactViewerPanel, /id="artifact-viewer"/);
  assert.match(artifactViewerPanel, /Euphony-inspired/);
  assert.match(artifactViewerPanel, /fetchRuntimeArtifactIndex/);
  assert.match(artifactViewerPanel, /fetchRuntimeArtifactDocument/);
  assert.match(artifactViewerPanel, /Open raw/);
  assert.match(artifactViewerPanel, /Copy JSON/);
  assert.match(artifactViewerPanel, /Quick views/);
  assert.match(artifactViewerPanel, /Structured snapshot/);
  assert.match(artifactViewerPanel, /initialArtifactPath\?: string \| null;/);
  assert.match(artifactViewerPanel, /initialArtifactIssue\?: string \| null;/);
  assert.match(artifactViewerPanel, /initialArtifactSection\?: string \| null;/);
  assert.match(artifactViewerPanel, /initialCaseRef\?: string \| null;/);
  assert.match(artifactViewerPanel, /initialFocusedOnly\?: boolean;/);
  assert.match(artifactViewerPanel, /onFocusedOnlyChange\?: \(enabled: boolean\) => void;/);
  assert.match(artifactViewerPanel, /buildRuntimeArtifactSectionAnchorId/);
  assert.match(artifactViewerPanel, /getRuntimeArtifactIssueConfig/);
  assert.match(artifactViewerPanel, /getRuntimeArtifactIssueFocusRowLabels/);
  assert.match(artifactViewerPanel, /getRuntimeArtifactIssueFocusSectionTitle/);
  assert.match(artifactViewerPanel, /buildRuntimeArtifactIssueSummary/);
  assert.match(artifactViewerPanel, /entry\.relativePath === initialArtifactPath/);
  assert.match(artifactViewerPanel, /const focusedSectionTitle = initialArtifactSection\?\.trim\(\) \|\| issueFocusSectionTitle;/);
  assert.match(artifactViewerPanel, /const focusedRowLabels = useMemo/);
  assert.match(artifactViewerPanel, /Focused by/);
  assert.match(artifactViewerPanel, /Focus summary/);
  assert.match(artifactViewerPanel, /Case ref/);
  assert.match(artifactViewerPanel, /Focus section/);
  assert.match(artifactViewerPanel, /Subsection anchor/);
  assert.match(artifactViewerPanel, /issueSummary\.headline/);
  assert.match(artifactViewerPanel, /issueSummary\.rows\.map/);
  assert.match(artifactViewerPanel, /const orderedStructuredSections = useMemo\(\(\) => \{/);
  assert.match(artifactViewerPanel, /const \[showFocusedOnly, setShowFocusedOnly\] = useState\(false\);/);
  assert.match(artifactViewerPanel, /const canShowFocusedOnly =/);
  assert.match(artifactViewerPanel, /const visibleStructuredSections = useMemo\(\(\) => \{/);
  assert.match(artifactViewerPanel, /const focusSection = structuredView\.sections\.find/);
  assert.match(artifactViewerPanel, /document\.getElementById\(sectionAnchorId\)\?\.scrollIntoView/);
  assert.match(artifactViewerPanel, /setShowFocusedOnly\(initialFocusedOnly && canShowFocusedOnly\);/);
  assert.match(artifactViewerPanel, /const toggleFocusedOnly = \(\) => \{/);
  assert.match(artifactViewerPanel, /onFocusedOnlyChange\?\.\(nextValue\);/);
  assert.match(artifactViewerPanel, /Show focused only/);
  assert.match(artifactViewerPanel, /Show all sections/);
  assert.match(artifactViewerPanel, /Showing only the focused structured lane for/);
  assert.match(artifactViewerPanel, /visibleStructuredSections\.map/);
  assert.match(artifactViewerPanel, /section\.title === focusedSectionTitle/);
  assert.match(artifactViewerPanel, /focusedRowLabels\.has\(row\.label\.trim\(\)\.toLowerCase\(\)\)/);
  assert.match(artifactViewerPanel, /focus/);
  assert.match(artifactViewerPanel, /Focus fields/);
  assert.match(artifactViewerPanel, /focus field/);
  assert.match(artifactViewerPanel, /issueSummary\.rows\.slice\(0, 4\)\.map/);
  assert.match(artifactViewerPanel, /focus-field-/);
  assert.match(artifactViewerPanel, /id=\{buildRuntimeArtifactSectionAnchorId\(section\.title\)\}/);
  assert.match(artifactViewerPanel, /Raw JSON focus:/);
  assert.match(artifactViewerPanel, /stays first in the structured snapshot above/);
  assert.match(artifactViewerLib, /export async function fetchRuntimeArtifactIndex/);
  assert.match(artifactViewerLib, /export async function fetchRuntimeArtifactDocument/);
  assert.match(artifactViewerLib, /export function summarizeRuntimeArtifact/);
  assert.match(artifactViewerLib, /export const PINNED_RUNTIME_ARTIFACT_PATHS = \[/);
  assert.match(artifactViewerLib, /export const RUNTIME_ARTIFACT_VIEW_PRESETS = \{/);
  assert.match(artifactViewerLib, /export type RuntimeArtifactIssue =/);
  assert.match(artifactViewerLib, /const RUNTIME_ARTIFACT_ISSUE_CONFIG:/);
  assert.match(artifactViewerLib, /export function isPinnedRuntimeArtifactPath/);
  assert.match(artifactViewerLib, /export function buildRuntimeArtifactViewerPath/);
  assert.match(artifactViewerLib, /section\?: string \| null \| undefined;/);
  assert.match(artifactViewerLib, /focusedOnly\?: boolean \| null \| undefined;/);
  assert.match(artifactViewerLib, /params\.set\("issue", options\.issue\);/);
  assert.match(artifactViewerLib, /params\.set\("section", options\.section\.trim\(\)\);/);
  assert.match(artifactViewerLib, /params\.set\("focusedOnly", "1"\);/);
  assert.match(artifactViewerLib, /export function buildRuntimeArtifactSectionAnchorId/);
  assert.match(artifactViewerLib, /export function getRuntimeArtifactIssueConfig/);
  assert.match(artifactViewerLib, /focusSectionTitle:/);
  assert.match(artifactViewerLib, /focusRowLabels: \[/);
  assert.match(artifactViewerLib, /export function getRuntimeArtifactIssueFocusSectionTitle/);
  assert.match(artifactViewerLib, /export function getRuntimeArtifactIssueFocusRowLabels/);
  assert.match(artifactViewerLib, /export type RuntimeArtifactIssueSummary =/);
  assert.match(artifactViewerLib, /Compliance blocker focus/);
  assert.match(artifactViewerLib, /Export posture focus/);
  assert.match(artifactViewerLib, /Raw artifact blocker focus/);
  assert.match(artifactViewerLib, /Case Wiki proof focus/);
  assert.match(artifactViewerLib, /export function buildRuntimeArtifactIssueSummary/);
  assert.match(artifactViewerLib, /export function buildRuntimeArtifactIssueViewerPath/);
  assert.match(artifactViewerLib, /section: config\?\.focusSectionTitle \?\? null,/);
  assert.match(artifactViewerLib, /export function buildRuntimeArtifactStructuredView/);
  assert.match(artifactViewerLib, /Unified release evidence report/);
  assert.match(artifactViewerLib, /Runtime proof lanes/);
  assert.match(artifactViewerLib, /release-evidence\/action-desk-kpi-report\.json/);
  assert.match(artifactViewerLib, /release-evidence\/consultation-booking-proof\.json/);
  assert.match(artifactViewerLib, /RUNTIME_ARTIFACT_VIEW_PRESETS = \{[\s\S]*actionDeskKpi:/);
  assert.match(artifactViewerLib, /RUNTIME_ARTIFACT_VIEW_PRESETS = \{[\s\S]*consultationBookingProof:/);
  assert.match(artifactViewerLib, /function buildActionDeskKpiStructuredView/);
  assert.match(artifactViewerLib, /Action Desk workflow KPI proof/);
  assert.match(artifactViewerLib, /function buildConsultationBookingProofStructuredView/);
  assert.match(artifactViewerLib, /Consultation booking proof posture/);
  assert.match(artifactViewerLib, /Calendar connector/);
  assert.match(bundlePage, /Inspect report/);
  assert.match(bundlePage, /RUNTIME_ARTIFACT_VIEW_PRESETS\.report/);
  assert.match(bundlePage, /buildRuntimeArtifactViewerPath/);
  assert.match(evidenceDetailPage, /Inspect badge details/);
  assert.match(evidenceDetailPage, /RUNTIME_ARTIFACT_VIEW_PRESETS\.badgeDetails/);
  assert.match(evidenceDetailPage, /buildRuntimeArtifactViewerPath/);

  assert.match(consolePage, /const \{ defaultConsoleCaseRef \} = useWorkspaceRuntime\(\);/);
  assert.match(consolePage, /const \{ hash \} = useLocation\(\);/);
  assert.match(consolePage, /const navigate = useNavigate\(\);/);
  assert.match(consolePage, /navigate\(`\/app\/console\/runtime\$\{search \? `\?\$\{search\}` : ""\}\$\{hash\}`/);
  assert.match(consolePage, /document\s*\.getElementById\(targetId\)\s*\?\.scrollIntoView/);
  assert.match(consolePage, /const caseRef = params\.get\("ref"\) \|\| defaultConsoleCaseRef \|\| "VS-2841";/);
});

test("shared app shell chrome reads runtime-backed counts, nodes, and diagnostics", () => {
  const topbar = readAppShellSource("components/workspace/Topbar.tsx");
  const sidebar = readAppShellSource("components/workspace/AppSidebar.tsx");
  const palette = readAppShellSource("components/workspace/CommandPalette.tsx");
  const rail = readAppShellSource("components/workspace/RuntimeRail.tsx");
  const nodeDetailRail = readAppShellSource("components/nodes/NodeDetailRail.tsx");

  assert.match(topbar, /const \{ runtimeActive, slaBurningCases, degradedInfraCases \} = useWorkspaceRuntime\(\);/);
  assert.match(topbar, /runtime · \{runtimeActive \? "live" : "mock"\}/);

  assert.match(sidebar, /const \{\s+cases,\s+deviceNodes,\s+pendingApprovals,\s+activeCaseCount,\s+pendingApprovalCount,/);
  assert.match(sidebar, /const runtimeSections: Section\[\] = \[/);
  assert.match(sidebar, /const runtimeOperatorSurfaces = operatorSurfaces\.map/);
  assert.match(sidebar, /Live activity", icon: Activity, url: "\/app"/);
  assert.match(sidebar, /Connections", icon: Plug, url: "\/app\/nodes"/);
  assert.match(sidebar, /Action queue"[\s\S]*url: "\/app\/console"/);
  assert.match(sidebar, /Safety rules", icon: ShieldCheck, url: "\/app\/simulation"/);
  assert.match(sidebar, /Health check", icon: HeartPulse, url: "\/app\/nodes"/);
  assert.match(sidebar, /const \{ pathname, hash \} = useLocation\(\);/);
  assert.match(sidebar, /pathname\.startsWith\("\/app\/console"\)/);
  assert.match(sidebar, /\/app\/console\?ref=\$\{encodeURIComponent\(firstPendingRef\)\}/);

  assert.match(palette, /const \{ cases, pendingApprovals \} = useWorkspaceRuntime\(\);/);
  assert.match(palette, /Start 7-minute demo/);
  assert.match(palette, /Local services dispatcher demo/);
  assert.match(palette, /Visa lead qualification/);
  assert.match(palette, /Missing-document follow-up/);
  assert.match(palette, /Consultation booking prep/);
  assert.match(palette, /CRM handoff summary/);
  assert.match(palette, /run\(\(\) => navigate\("\/app\?demo=visa-intake"\)\)/);
  assert.match(palette, /run\(\(\) => navigate\("\/app\?demo=local-services-dispatch&service=ac-repair-dispatch"\)\)/);
  assert.match(palette, /navigate\(`\/app\/console\?ref=\$\{leadQualificationCase\.ref\}`\)/);
  assert.match(palette, /navigate\(`\/app\/console\?ref=\$\{missingDocumentsCase\.ref\}&focus=documents`\)/);
  assert.match(palette, /navigate\(buildCaseBundlePath\(consultationCase\)\)/);
  assert.match(palette, /navigate\(buildCaseVaultPath\(crmHandoffCase\)\)/);
  assert.match(palette, /run\(\(\) => navigate\("\/app\/nodes"\)\)/);
  assert.match(palette, /run\(\(\) => navigate\("\/app\/console\/runtime"\)\)/);
  assert.match(palette, /run\(\(\) => navigate\("\/app\/console\/runtime#artifact-viewer"\)\)/);

  assert.match(rail, /const \{\s+runtimeActive,\s+pendingApprovalCount,\s+runtimeDiagnostics,\s+bootstrapDoctor,\s+browserWorkers,\s+\} = useWorkspaceRuntime\(\);/);
  assert.match(rail, /const items: RailItem\[\] = runtimeActive/);

  assert.match(nodeDetailRail, /const \{ cases \} = useWorkspaceRuntime\(\);/);
  assert.match(nodeDetailRail, /cases\.filter\(\(c\) => c\.sourceNodeId === node\.id\)/);
});

test("runtime app shell resolves backend endpoints through runtime config and shared node helpers", () => {
  const workspaceRuntime = readAppShellSource("hooks/useWorkspaceRuntime.tsx");
  const runtimeNodes = readAppShellSource("lib/runtime-device-nodes.ts");
  const nodesPage = readAppShellSource("pages/Nodes.tsx");

  assert.match(workspaceRuntime, /import \{ fetchRuntimeApi \} from "@\/lib\/runtime-api";/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/operator\/summary"/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/governance\/policy"/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/sessions\?limit=8"/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*`\/v1\/runtime\/case-wiki\?sessionId=\$\{encodeURIComponent\(sessionId\)\}`/);

  assert.match(runtimeNodes, /import \{ fetchRuntimeApi \} from "@\/lib\/runtime-api";/);
  assert.match(runtimeNodes, /fetchRuntimeApi\(\s*"\/v1\/device-nodes\?includeOffline=true&limit=200"/);

  assert.match(nodesPage, /import \{\s*fetchRuntimeDeviceNodes,\s*mapRuntimeDeviceNode,\s*\} from "@\/lib\/runtime-device-nodes";/);
  assert.doesNotMatch(nodesPage, /async function fetchRuntimeDeviceNodes\(\)/);
});

test("live desk, operator console, and simulation drilldowns share case-driven judge artifact links", () => {
  const helper = readAppShellSource("lib/case-artifact-links.ts");
  const liveDesk = readAppShellSource("components/workspace/LiveDesk.tsx");
  const consoleStage = readAppShellSource("components/workspace/ConsoleStage.tsx");
  const runDetailDrawer = readAppShellSource("components/workspace/RunDetailDrawer.tsx");
  const readme = readRepoSource("README.md");
  const operatorGuide = readRepoSource("docs/operator-guide.md");

  assert.match(helper, /export function resolveCaseArtifactRef/);
  assert.match(helper, /return firstArtifactToken\(target\.caseId, target\.sessionId, target\.ref\);/);
  assert.match(helper, /export function buildCaseBundlePath/);
  assert.match(helper, /export function buildCaseEvidencePath/);
  assert.match(helper, /export function buildCaseRuntimeSupportPath/);
  assert.match(helper, /return `\/app\/console\/runtime\$\{search\}\$\{anchor\}`;/);

  assert.match(liveDesk, /import \{\s*buildCaseBundlePath,\s*buildCaseEvidencePath,\s*buildCaseVaultPath,\s*\} from "@\/lib\/case-artifact-links";/);
  assert.match(liveDesk, /navigate\(buildCaseBundlePath\(value\)\);/);
  assert.match(liveDesk, /navigate\(buildCaseEvidencePath\(value\)\);/);
  assert.match(liveDesk, /navigate\(buildCaseVaultPath\(value\)\);/);

  assert.match(consoleStage, /import \{\s*buildCaseBundlePath,\s*buildCaseEvidencePath,\s*buildCaseRuntimeSupportPath,\s*buildCaseVaultPath,\s*\} from "@\/lib\/case-artifact-links";/);
  assert.match(consoleStage, /import \{ useQuery \} from "@tanstack\/react-query";/);
  assert.match(consoleStage, /import \{\s*buildRuntimeSessionReplaySummary,\s*fetchRuntimeSessionReplay,\s*type RuntimeSessionReplaySummary,\s*\} from "@\/lib\/runtime-session-replay";/);
  assert.match(consoleStage, /const \{ deviceNodes, getCaseByRef, getCaseWikiByRef \} = useWorkspaceRuntime\(\);/);
  assert.match(consoleStage, /navigate\(buildCaseBundlePath\(c\)\);/);
  assert.match(consoleStage, /navigate\(buildCaseEvidencePath\(c\)\);/);
  assert.match(consoleStage, /navigate\(buildCaseVaultPath\(c\)\);/);
  assert.match(consoleStage, /const runtimeSupportPath = buildCaseRuntimeSupportPath\(c\);/);
  assert.match(consoleStage, /Runtime support/);
  assert.match(consoleStage, /Export blocked|Export ready|Export waiting/);
  assert.match(consoleStage, /Proof signed|Proof published|Proof pending/);
  assert.match(consoleStage, /Replay loading|Replay waiting/);
  assert.match(consoleStage, /Gate pending/);
  assert.match(consoleStage, /showRuntimeSupportStrip \? \(/);
  assert.match(consoleStage, /Inspect compliance blocker|Inspect export block|Inspect export posture|Inspect unsigned proof|Inspect missing proof|Inspect replay gate|Inspect replay/);

  assert.match(runDetailDrawer, /import \{\s*buildCaseBundlePath,\s*buildCaseEvidencePath,\s*\} from "@\/lib\/case-artifact-links";/);
  assert.match(runDetailDrawer, /navigate\(buildCaseBundlePath\(c \?\? run\.caseRef\)\);/);
  assert.match(runDetailDrawer, /navigate\(buildCaseEvidencePath\(c \?\? run\.caseRef\)\);/);

  assert.match(readme, /Live Desk` row actions\/context menus and `Operator Console` hero quick actions/);
  assert.match(readme, /\/bundle\/:id` and `\/evidence\/:id` prefer runtime `caseId\/sessionId` targets/);
  assert.match(operatorGuide, /Operator proof-link note:/);
  assert.match(operatorGuide, /Presentation Bundle` \/ `Visual Evidence` targets through the same repo-owned `caseId\/sessionId\/ref` resolver/);
});

test("live desk exposes the seven-minute visa intake product path", () => {
  const liveDesk = readAppShellSource("components/workspace/LiveDesk.tsx");
  const readme = readRepoSource("README.md");
  const localDevelopment = readRepoSource("docs/local-development.md");
  const operatorGuide = readRepoSource("docs/operator-guide.md");
  const simplificationPlan = readRepoSource("docs/quality-simplification-plan.md");
  const gettingStarted = readRepoSource("docs/getting-started-7-min.md");
  const localServicesSpec = readRepoSource("docs/local-services-action-desk-spec.md");
  const pilotOffer = readRepoSource("docs/local-services-pilot-offer.md");
  const demoScript = readRepoSource("docs/local-services-demo-script.md");
  const outreachList = readRepoSource("docs/local-services-outreach-list.md");
  const pilotScorecard = readRepoSource("docs/local-services-pilot-scorecard.md");
  const pilotRunbook = readRepoSource("docs/local-services-pilot-runbook.md");

  assert.match(liveDesk, /const visaIntakeDemo = searchParams\.get\("demo"\) === "visa-intake";/);
  assert.match(liveDesk, /const localServicesDispatchDemo = searchParams\.get\("demo"\) === "local-services-dispatch";/);
  assert.match(liveDesk, /const activeLocalServiceId = searchParams\.get\("service"\);/);
  assert.match(liveDesk, /const openVisaIntakeDemo = \(\) => \{/);
  assert.match(liveDesk, /const openLocalServicesDispatchDemo = \(\) => \{/);
  assert.match(liveDesk, /next\.set\("demo", "local-services-dispatch"\);/);
  assert.match(liveDesk, /next\.set\("service", "ac-repair-dispatch"\);/);
  assert.match(liveDesk, /const SevenMinuteVisaIntakePanel = \(\{/);
  assert.match(liveDesk, /const LocalServicesDispatchDemoPanel = \(\{/);
  assert.match(liveDesk, /Case Outcome Summary/);
  assert.match(liveDesk, /AI Dispatcher for Local Services/);
  assert.match(liveDesk, /Phone AI intake/);
  assert.match(liveDesk, /Operator-approved booking/);
  assert.match(liveDesk, /AC repair dispatch/);
  assert.match(liveDesk, /Plumbing emergency/);
  assert.match(liveDesk, /Cleaning quote and booking/);
  assert.match(liveDesk, /Measurement visit booking/);
  assert.match(liveDesk, /construction-adjacent P0/i);
  assert.match(liveDesk, /No material availability, installation date, or final price is promised/);
  assert.match(liveDesk, /Pricing and slot inputs/);
  assert.match(liveDesk, /Customer confirmation draft/);
  assert.match(liveDesk, /Master\/operator handoff/);
  assert.match(liveDesk, /Telegram intake prototype/);
  assert.match(liveDesk, /Normalized fields/);
  assert.match(liveDesk, /Reply draft/);
  assert.match(liveDesk, /Pilot readiness/);
  assert.match(liveDesk, /One-page offer/);
  assert.match(liveDesk, /90-second demo script/);
  assert.match(liveDesk, /Outreach focus/);
  assert.match(liveDesk, /Launch checklist/);
  assert.match(liveDesk, /Open offer doc/);
  assert.match(liveDesk, /Open demo script/);
  assert.match(liveDesk, /Open outreach list/);
  assert.match(liveDesk, /Open pilot scorecard/);
  assert.match(liveDesk, /Pilot outreach wizard/);
  assert.match(liveDesk, /Offer preview/);
  assert.match(liveDesk, /Audience from outreach list/);
  assert.match(liveDesk, /Test message preview/);
  assert.match(liveDesk, /Operator confirmation/);
  assert.match(liveDesk, /operator-approved/);
  assert.match(liveDesk, /type LocalServiceOutreachProspect = \{/);
  assert.match(liveDesk, /type LocalServicePilotWorkspaceState = \{/);
  assert.match(liveDesk, /type LocalServicePilotMetricStatus =/);
  assert.match(liveDesk, /metricStatusByService/);
  assert.match(liveDesk, /LOCAL_SERVICE_PILOT_WORKSPACE_STORAGE_KEY = "liveDesk:localServicesPilotWorkspace:v1"/);
  assert.match(liveDesk, /LOCAL_SERVICE_PILOT_STATUS_ORDER/);
  assert.match(liveDesk, /LOCAL_SERVICE_PILOT_METRIC_STATUS_ACTIONS/);
  assert.match(liveDesk, /readLocalServicePilotWorkspaceState/);
  assert.match(liveDesk, /window\.localStorage\.setItem\(LOCAL_SERVICE_PILOT_WORKSPACE_STORAGE_KEY/);
  assert.match(liveDesk, /allPilotProspects/);
  assert.match(liveDesk, /pilotFunnelCounts/);
  assert.match(liveDesk, /nextManualBatch/);
  assert.match(liveDesk, /Pilot funnel summary/);
  assert.match(liveDesk, /All candidates/);
  assert.match(liveDesk, /Next manual batch/);
  assert.match(liveDesk, /Manual execution rule/);
  assert.match(liveDesk, /Open pilot export/);
  assert.match(liveDesk, /Pilot workspace export drawer/);
  assert.match(liveDesk, /Copy pilot workspace export/);
  assert.match(liveDesk, /no_crm_write/);
  assert.match(liveDesk, /Pilot metrics tracker/);
  assert.match(liveDesk, /Open metrics tracker/);
  assert.match(liveDesk, /Copy pilot metrics tracker/);
  assert.match(liveDesk, /local_services_pilot_metrics_tracker/);
  assert.match(liveDesk, /Metric capture state/);
  assert.match(liveDesk, /Mark baseline captured/);
  assert.match(liveDesk, /Mark tracking live/);
  assert.match(liveDesk, /Mark review ready/);
  assert.match(liveDesk, /Reset metrics/);
  assert.match(liveDesk, /browser-local/);
  assert.match(liveDesk, /Pilot scorecard action/);
  assert.match(liveDesk, /Selected company/);
  assert.match(liveDesk, /AC MASTER/);
  assert.match(liveDesk, /Santexniki\.uz/);
  assert.match(liveDesk, /Service-Pro/);
  assert.match(liveDesk, /Pilot workspace state/);
  assert.match(liveDesk, /Saved in this browser/);
  assert.match(liveDesk, /Draft ready/);
  assert.match(liveDesk, /Mark manually contacted/);
  assert.match(liveDesk, /Mark reply received/);
  assert.match(liveDesk, /Reject for now/);
  assert.match(liveDesk, /Reset to not contacted/);
  assert.match(liveDesk, /Record scorecard draft/);
  assert.match(liveDesk, /Pilot workspace state persisted locally/);
  assert.match(liveDesk, /No outbound message sent/);
  assert.match(liveDesk, /Confirm manually/);
  assert.match(liveDesk, /Log outcome in scorecard/);
  assert.match(liveDesk, /path\.startsWith\("\/workspace-docs\/"\)/);
  assert.match(liveDesk, /window\.location\.assign\(path\)/);
  assert.match(liveDesk, /LOCAL_SERVICES_PILOT_OFFER_PATH = "\/workspace-docs\/local-services-pilot-offer\.md"/);
  assert.match(liveDesk, /LOCAL_SERVICES_DEMO_SCRIPT_PATH = "\/workspace-docs\/local-services-demo-script\.md"/);
  assert.match(liveDesk, /LOCAL_SERVICES_OUTREACH_LIST_PATH = "\/workspace-docs\/local-services-outreach-list\.md"/);
  assert.match(liveDesk, /LOCAL_SERVICES_PILOT_SCORECARD_PATH = "\/workspace-docs\/local-services-pilot-scorecard\.md"/);
  assert.match(liveDesk, /Pilot metrics/);
  assert.match(liveDesk, /Missed-call recovery/);
  assert.match(liveDesk, /Manual operator edits/);
  assert.match(liveDesk, /No-show \/ cancellation/);
  assert.match(liveDesk, /pilotKit/);
  assert.match(liveDesk, /launchChecklist/);
  assert.match(liveDesk, /telegramIntake/);
  assert.match(liveDesk, /telegram_intake: template\.detail\.telegramIntake/);
  assert.match(liveDesk, /Dispatch payload preview/);
  assert.match(liveDesk, /Copy dispatch payload/);
  assert.match(liveDesk, /Open dispatch drawer/);
  assert.match(liveDesk, /Open customer drawer/);
  assert.match(liveDesk, /Open handoff drawer/);
  assert.match(liveDesk, /Dispatch payload drawer/);
  assert.match(liveDesk, /Customer confirmation drawer/);
  assert.match(liveDesk, /Master\/operator handoff drawer/);
  assert.match(liveDesk, /LocalServiceDispatchDrawer/);
  assert.match(liveDesk, /type LocalServiceExportKind = "dispatch" \| "customer" \| "handoff";/);
  assert.match(liveDesk, /type LocalServicePayloadPreview = \{/);
  assert.match(liveDesk, /type LocalServiceDispatchExport = \{/);
  assert.match(liveDesk, /function buildLocalServicePayloadPreview\(/);
  assert.match(liveDesk, /function buildLocalServiceDispatchExport\(/);
  assert.match(liveDesk, /Local services dispatch export/);
  assert.match(liveDesk, /Dispatch export mode/);
  assert.match(liveDesk, /Operator approval checklist/);
  assert.match(liveDesk, /Copy dispatch export/);
  assert.match(liveDesk, /Copy customer confirmation/);
  assert.match(liveDesk, /Copy master handoff/);
  assert.match(liveDesk, /export_kind: kind/);
  assert.match(liveDesk, /operator_required_before_customer_or_master_send/);
  assert.match(liveDesk, /Dispatch payload copied/);
  assert.match(liveDesk, /title: `\$\{label\} copied`/);
  assert.match(liveDesk, /handoff_status: "approval_required"/);
  assert.match(liveDesk, /approval_policy/);
  assert.match(liveDesk, /evidence_link/);
  assert.match(liveDesk, /bundle_path/);
  assert.match(liveDesk, /buildCaseEvidencePath\("LS-7101"\)/);
  assert.match(liveDesk, /buildCaseBundlePath\("LS-7302"\)/);
  assert.match(liveDesk, /Playbook templates/);
  assert.match(liveDesk, /const activePlaybookId = searchParams\.get\("playbook"\);/);
  assert.match(liveDesk, /Visa lead qualification/);
  assert.match(liveDesk, /Missing-document follow-up/);
  assert.match(liveDesk, /Consultation booking prep/);
  assert.match(liveDesk, /CRM handoff summary/);
  assert.match(liveDesk, /highlights: \[/);
  assert.match(liveDesk, /label: "Outcome"/);
  assert.match(liveDesk, /label: "Approval"/);
  assert.match(liveDesk, /label: "Evidence"/);
  assert.match(liveDesk, /label: "Deliverable"/);
  assert.match(liveDesk, /Console review only/);
  assert.match(liveDesk, /Reminder queued/);
  assert.match(liveDesk, /Protected follow-up/);
  assert.match(liveDesk, /Presentation bundle/);
  assert.match(liveDesk, /CRM-ready handoff/);
  assert.match(liveDesk, /Resolved case proof/);
  assert.match(liveDesk, /Sample input/);
  assert.match(liveDesk, /Approval policy/);
  assert.match(liveDesk, /Evidence output/);
  assert.match(liveDesk, /CRM fields/);
  assert.match(liveDesk, /Payload preview/);
  assert.match(liveDesk, /Surface path/);
  assert.match(liveDesk, /Copy payload/);
  assert.match(liveDesk, /Open export drawer/);
  assert.match(liveDesk, /CRM payload drawer/);
  assert.match(liveDesk, /Consultation handoff drawer/);
  assert.match(liveDesk, /Human-readable/);
  assert.match(liveDesk, /JSON/);
  assert.match(liveDesk, /Integration-ready export/);
  assert.match(liveDesk, /Operator review checklist/);
  assert.match(liveDesk, /Selected template/);
  assert.match(liveDesk, /Inspect template/);
  assert.match(liveDesk, /type PlaybookPayloadPreview = \{/);
  assert.match(liveDesk, /type PlaybookExportMode = "human" \| "json";/);
  assert.match(liveDesk, /type PlaybookOperatorExport = \{/);
  assert.match(liveDesk, /function buildPlaybookPayloadPreview\(/);
  assert.match(liveDesk, /function buildPlaybookOperatorExport\(/);
  assert.match(liveDesk, /const PlaybookTemplateDetailPanel = \(\{/);
  assert.match(liveDesk, /const PlaybookExportDrawer = \(\{/);
  assert.match(liveDesk, /payloadPreview: PlaybookPayloadPreview;/);
  assert.match(liveDesk, /onCopyPayload: \(\) => void;/);
  assert.match(liveDesk, /onOpenExportDrawer: \(\) => void;/);
  assert.match(liveDesk, /next\.set\("playbook", "missing-documents"\);/);
  assert.match(liveDesk, /next\.set\("playbook", template\.id\);/);
  assert.match(liveDesk, /lead_status/);
  assert.match(liveDesk, /follow_up_status/);
  assert.match(liveDesk, /consultation_at/);
  assert.match(liveDesk, /case_status/);
  assert.match(liveDesk, /delivery_channel/);
  assert.match(liveDesk, /surface_path/);
  assert.match(liveDesk, /approval_owner/);
  assert.match(liveDesk, /bundle_path/);
  assert.match(liveDesk, /navigator\.clipboard\.writeText/);
  assert.match(liveDesk, /title: "Payload copied"/);
  assert.match(liveDesk, /title: `\$\{label\} copied`/);
  assert.match(liveDesk, /setPlaybookExportMode\(activePlaybookTemplate\?\.id === "crm-handoff" \? "json" : "human"\);/);
  assert.match(liveDesk, /navigate\(activePlaybookPayloadPreview\.surfacePath\);/);
  assert.match(liveDesk, /Review approval/);
  assert.match(liveDesk, /Start 7-minute demo/);
  assert.match(liveDesk, /Exit demo/);
  assert.match(liveDesk, /Presentation bundle/);
  assert.match(liveDesk, /Evidence bundle/);
  assert.match(liveDesk, /cases\.find\(\(c\) => c\.ref === "VS-2841"\)/);
  assert.match(liveDesk, /cases\.find\(\(c\) => c\.ref === "VS-2838"\)/);
  assert.match(liveDesk, /cases\.find\(\(c\) => c\.ref === "VS-2840"\)/);
  assert.match(liveDesk, /cases\.find\(\(c\) => c\.ref === "VS-2837"\)/);
  assert.match(liveDesk, /next\.set\("demo", "visa-intake"\);/);
  assert.match(liveDesk, /navigate\(`\/app\/console\?ref=\$\{encodeURIComponent\(visaIntakeDemoCase\.ref\)\}&focus=approval`\)/);
  assert.match(liveDesk, /navigate\(`\/app\/console\?ref=\$\{encodeURIComponent\(leadQualificationCase\.ref\)\}`\)/);
  assert.match(liveDesk, /navigate\(`\/app\/console\?ref=\$\{encodeURIComponent\(missingDocumentsCase\.ref\)\}&focus=documents`\)/);
  assert.match(liveDesk, /navigate\(buildCaseBundlePath\(consultationCase\)\)/);
  assert.match(liveDesk, /navigate\(buildCaseVaultPath\(crmHandoffCase\)\)/);
  assert.match(liveDesk, /navigate\(buildCaseBundlePath\(visaIntakeDemoCase\)\)/);
  assert.match(liveDesk, /navigate\(buildCaseEvidencePath\(visaIntakeDemoCase\)\)/);
  assert.match(liveDesk, /navigate\(buildCaseVaultPath\(visaIntakeDemoCase\)\)/);

  assert.match(readme, /Seven-minute product path:/);
  assert.match(readme, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(readme, /AI Dispatcher for local service businesses/);
  assert.match(readme, /AC repair dispatch/);
  assert.match(readme, /Plumbing emergency/);
  assert.match(readme, /Cleaning quote and booking/);
  assert.match(readme, /Measurement visit booking/);
  assert.match(readme, /construction-material quote and delivery stays out of P0/);
  assert.match(readme, /operator-approved/);
  assert.match(readme, /Open dispatch drawer/);
  assert.match(readme, /Open customer\s+drawer/);
  assert.match(readme, /Open handoff drawer/);
  assert.match(readme, /Telegram intake prototype/);
  assert.match(readme, /Pilot readiness/);
  assert.match(readme, /One-page offer/);
  assert.match(readme, /90-second demo script/);
  assert.match(readme, /Launch checklist/);
  assert.match(readme, /Pilot metrics/);
  assert.match(readme, /Pilot outreach wizard/);
  assert.match(readme, /Audience from outreach list/);
  assert.match(readme, /Test message preview/);
  assert.match(readme, /Operator confirmation/);
  assert.match(readme, /Pilot scorecard action/);
  assert.match(readme, /Record scorecard draft/);
  assert.match(readme, /Not contacted/);
  assert.match(readme, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(readme, /Draft ready/);
  assert.match(readme, /Contacted manually/);
  assert.match(readme, /Reply received/);
  assert.match(readme, /Rejected for now/);
  assert.match(readme, /Pilot funnel summary/);
  assert.match(readme, /All candidates/);
  assert.match(readme, /Next manual batch/);
  assert.match(readme, /Pilot workspace export drawer/);
  assert.match(readme, /Copy pilot workspace export/);
  assert.match(readme, /Pilot metrics tracker/);
  assert.match(readme, /Copy pilot metrics tracker/);
  assert.match(readme, /\/workspace-docs\/local-services-pilot-offer\.md/);
  assert.match(readme, /\/workspace-docs\/local-services-demo-script\.md/);
  assert.match(readme, /\/workspace-docs\/local-services-outreach-list\.md/);
  assert.match(readme, /\/workspace-docs\/local-services-pilot-scorecard\.md/);
  assert.match(readme, /docs\/local-services-pilot-runbook\.md/);
  assert.match(readme, /Start 7-minute demo/);
  assert.match(readme, /Live Desk also exposes four productized playbook templates/);
  assert.match(readme, /Outcome`, `Approval`, `Evidence`, and `Deliverable/);
  assert.match(readme, /Selecting a template opens an inline detail panel/);
  assert.match(readme, /\/app\?playbook=<lane-id>/);
  assert.match(readme, /Payload preview`, `Surface path`, and/);
  assert.match(readme, /Copy payload/);
  assert.match(readme, /Open export drawer/);
  assert.match(readme, /CRM payload drawer/);
  assert.match(readme, /Consultation handoff drawer/);
  assert.match(readme, /Human-readable` and `JSON`/);
  assert.match(localDevelopment, /\/app\?demo=visa-intake/);
  assert.match(localDevelopment, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(localDevelopment, /AI Dispatcher for Local Services/);
  assert.match(localDevelopment, /Measurement visit booking/);
  assert.match(localDevelopment, /measurement lane is construction-adjacent P0/);
  assert.match(localDevelopment, /Dispatch payload preview/);
  assert.match(localDevelopment, /Open dispatch drawer/);
  assert.match(localDevelopment, /Open customer drawer/);
  assert.match(localDevelopment, /Open handoff drawer/);
  assert.match(localDevelopment, /Telegram intake prototype/);
  assert.match(localDevelopment, /Pilot readiness/);
  assert.match(localDevelopment, /One-page offer/);
  assert.match(localDevelopment, /90-second demo script/);
  assert.match(localDevelopment, /Launch checklist/);
  assert.match(localDevelopment, /Pilot metrics/);
  assert.match(localDevelopment, /Pilot outreach wizard/);
  assert.match(localDevelopment, /Audience from outreach list/);
  assert.match(localDevelopment, /Test message preview/);
  assert.match(localDevelopment, /Operator confirmation/);
  assert.match(localDevelopment, /Pilot scorecard action/);
  assert.match(localDevelopment, /Selected company/);
  assert.match(localDevelopment, /Record scorecard draft/);
  assert.match(localDevelopment, /Pilot workspace state/);
  assert.match(localDevelopment, /Saved in this browser/);
  assert.match(localDevelopment, /Contacted manually/);
  assert.match(localDevelopment, /Reply received/);
  assert.match(localDevelopment, /Rejected for now/);
  assert.match(localDevelopment, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(localDevelopment, /Pilot funnel summary/);
  assert.match(localDevelopment, /All candidates/);
  assert.match(localDevelopment, /Next manual batch/);
  assert.match(localDevelopment, /Manual execution rule/);
  assert.match(localDevelopment, /Open pilot export/);
  assert.match(localDevelopment, /Open metrics tracker/);
  assert.match(localDevelopment, /No outbound message sent/);
  assert.match(localDevelopment, /Open offer doc/);
  assert.match(localDevelopment, /Open demo script/);
  assert.match(localDevelopment, /Open outreach list/);
  assert.match(localDevelopment, /Open pilot scorecard/);
  assert.match(localDevelopment, /http:\/\/localhost:3000\/workspace-docs\/local-services-pilot-offer\.md/);
  assert.match(localDevelopment, /http:\/\/localhost:3000\/workspace-docs\/local-services-demo-script\.md/);
  assert.match(localDevelopment, /http:\/\/localhost:3000\/workspace-docs\/local-services-pilot-runbook\.md/);
  assert.match(localDevelopment, /Start 7-minute demo/);
  assert.match(localDevelopment, /Visa lead qualification/);
  assert.match(localDevelopment, /Each template card previews `Outcome`, `Approval`, `Evidence`, and `Deliverable`/);
  assert.match(localDevelopment, /inline detail panel with `Sample input`, `Approval policy`, `Evidence output`, and `CRM fields`/);
  assert.match(localDevelopment, /real `Payload preview`, `Surface path`, and `Copy payload` action/);
  assert.match(localDevelopment, /Open export drawer/);
  assert.match(localDevelopment, /`CRM payload drawer` and `Consultation handoff drawer`/);
  assert.match(localDevelopment, /\?playbook=<lane-id>/);
  assert.match(operatorGuide, /Seven-minute demo note:/);
  assert.match(operatorGuide, /Local-services demo note:/);
  assert.match(operatorGuide, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(operatorGuide, /AI Dispatcher\s+for Local Services/);
  assert.match(operatorGuide, /Start 7-minute\s+demo/);
  assert.match(operatorGuide, /Open dispatch drawer/);
  assert.match(operatorGuide, /Open customer drawer/);
  assert.match(operatorGuide, /Open handoff drawer/);
  assert.match(operatorGuide, /Telegram intake prototype/);
  assert.match(operatorGuide, /Pilot readiness/);
  assert.match(operatorGuide, /One-page offer/);
  assert.match(operatorGuide, /90-second demo script/);
  assert.match(operatorGuide, /Launch checklist/);
  assert.match(operatorGuide, /Pilot metrics/);
  assert.match(operatorGuide, /Pilot outreach wizard/);
  assert.match(operatorGuide, /Audience from outreach list/);
  assert.match(operatorGuide, /Test message preview/);
  assert.match(operatorGuide, /Operator confirmation/);
  assert.match(operatorGuide, /Pilot scorecard action/);
  assert.match(operatorGuide, /Record scorecard draft/);
  assert.match(operatorGuide, /Not contacted/);
  assert.match(operatorGuide, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(operatorGuide, /Draft ready/);
  assert.match(operatorGuide, /Contacted manually/);
  assert.match(operatorGuide, /Reply received/);
  assert.match(operatorGuide, /Rejected for now/);
  assert.match(operatorGuide, /Pilot funnel summary/);
  assert.match(operatorGuide, /All candidates/);
  assert.match(operatorGuide, /Next manual batch/);
  assert.match(operatorGuide, /Pilot workspace export drawer/);
  assert.match(operatorGuide, /Copy pilot workspace export/);
  assert.match(operatorGuide, /Pilot metrics tracker/);
  assert.match(operatorGuide, /Copy pilot metrics tracker/);
  assert.match(operatorGuide, /Open offer doc/);
  assert.match(operatorGuide, /Open demo script/);
  assert.match(operatorGuide, /Open outreach list/);
  assert.match(operatorGuide, /Open pilot scorecard/);
  assert.match(operatorGuide, /docs\/local-services-pilot-runbook\.md/);
  assert.match(operatorGuide, /14-day operating\s+sequence/);
  assert.match(operatorGuide, /Each card previews `Outcome`, `Approval`, `Evidence`,/);
  assert.match(operatorGuide, /inline detail panel with `Sample input`, `Approval\s+policy`, `Evidence output`, and `CRM fields`/);
  assert.match(operatorGuide, /`Payload preview`, `Surface path`, and `Copy payload` action/);
  assert.match(operatorGuide, /Open export drawer/);
  assert.match(operatorGuide, /CRM payload\s+drawer/);
  assert.match(operatorGuide, /Consultation handoff drawer/);
  assert.match(operatorGuide, /\/app\?playbook=<lane-id>/);
  assert.match(simplificationPlan, /\/app\?demo=visa-intake/);
  assert.match(simplificationPlan, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(simplificationPlan, /phone-first and operator-approved/);
  assert.match(simplificationPlan, /Open dispatch drawer/);
  assert.match(simplificationPlan, /Open customer drawer/);
  assert.match(simplificationPlan, /Open handoff drawer/);
  assert.match(simplificationPlan, /Telegram intake prototype/);
  assert.match(simplificationPlan, /Pilot readiness/);
  assert.match(simplificationPlan, /One-page offer/);
  assert.match(simplificationPlan, /90-second demo script/);
  assert.match(simplificationPlan, /Launch checklist/);
  assert.match(simplificationPlan, /Pilot metrics/);
  assert.match(simplificationPlan, /Pilot outreach wizard/);
  assert.match(simplificationPlan, /Audience from outreach list/);
  assert.match(simplificationPlan, /Test message preview/);
  assert.match(simplificationPlan, /Operator confirmation/);
  assert.match(simplificationPlan, /Pilot scorecard action/);
  assert.match(simplificationPlan, /Record scorecard draft/);
  assert.match(simplificationPlan, /Not contacted/);
  assert.match(simplificationPlan, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(simplificationPlan, /Draft ready/);
  assert.match(simplificationPlan, /Contacted manually/);
  assert.match(simplificationPlan, /Reply received/);
  assert.match(simplificationPlan, /Rejected for now/);
  assert.match(simplificationPlan, /Pilot funnel summary/);
  assert.match(simplificationPlan, /All candidates/);
  assert.match(simplificationPlan, /Next manual batch/);
  assert.match(simplificationPlan, /Open pilot export/);
  assert.match(simplificationPlan, /Pilot workspace export\s+drawer/);
  assert.match(simplificationPlan, /Pilot metrics tracker/);
  assert.match(simplificationPlan, /\/workspace-docs\/local-services-pilot-offer\.md/);
  assert.match(simplificationPlan, /\/workspace-docs\/local-services-demo-script\.md/);
  assert.match(simplificationPlan, /\/workspace-docs\/local-services-outreach-list\.md/);
  assert.match(simplificationPlan, /\/workspace-docs\/local-services-pilot-scorecard\.md/);
  assert.match(simplificationPlan, /\/workspace-docs\/local-services-pilot-runbook\.md/);
  assert.match(simplificationPlan, /productized launch cards/);
  assert.match(simplificationPlan, /Each card should preview `Outcome`, `Approval`, `Evidence`,/);
  assert.match(simplificationPlan, /The selected lane should\s+also expose `Sample input`, `Approval policy`, `Evidence output`, and `CRM\s+fields` inline/);
  assert.match(simplificationPlan, /repo-owned `Payload preview`, the canonical `Surface path`, and a\s+`Copy payload` action/);
  assert.match(simplificationPlan, /Open export drawer/);
  assert.match(simplificationPlan, /CRM payload drawer/);
  assert.match(simplificationPlan, /Consultation handoff drawer/);
  assert.match(simplificationPlan, /\?playbook=/);
  assert.match(gettingStarted, /Start 7-minute demo/);
  assert.match(gettingStarted, /Local Services Expansion Path/);
  assert.match(gettingStarted, /Local services demo/);
  assert.match(gettingStarted, /AC repair dispatch/);
  assert.match(gettingStarted, /Plumbing emergency/);
  assert.match(gettingStarted, /Cleaning quote and booking/);
  assert.match(gettingStarted, /Measurement visit booking/);
  assert.match(gettingStarted, /Construction-material commerce is intentionally not in this first path/);
  assert.match(gettingStarted, /Dispatch payload preview/);
  assert.match(gettingStarted, /Open dispatch drawer/);
  assert.match(gettingStarted, /Open customer drawer/);
  assert.match(gettingStarted, /Open handoff drawer/);
  assert.match(gettingStarted, /Telegram intake prototype/);
  assert.match(gettingStarted, /Pilot readiness/);
  assert.match(gettingStarted, /One-page offer/);
  assert.match(gettingStarted, /90-second demo script/);
  assert.match(gettingStarted, /Launch checklist/);
  assert.match(gettingStarted, /Pilot metrics/);
  assert.match(gettingStarted, /Pilot outreach wizard/);
  assert.match(gettingStarted, /Audience from outreach list/);
  assert.match(gettingStarted, /Test message preview/);
  assert.match(gettingStarted, /Operator confirmation/);
  assert.match(gettingStarted, /Pilot scorecard action/);
  assert.match(gettingStarted, /AC MASTER/);
  assert.match(gettingStarted, /Santexniki\.uz/);
  assert.match(gettingStarted, /Service-Pro/);
  assert.match(gettingStarted, /Record scorecard draft/);
  assert.match(gettingStarted, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(gettingStarted, /Draft ready/);
  assert.match(gettingStarted, /Contacted manually/);
  assert.match(gettingStarted, /Reply received/);
  assert.match(gettingStarted, /Rejected for now/);
  assert.match(gettingStarted, /Pilot funnel summary/);
  assert.match(gettingStarted, /All candidates/);
  assert.match(gettingStarted, /Next manual batch/);
  assert.match(gettingStarted, /Open pilot export/);
  assert.match(gettingStarted, /Copy pilot workspace export/);
  assert.match(gettingStarted, /Open metrics tracker/);
  assert.match(gettingStarted, /Copy pilot metrics tracker/);
  assert.match(gettingStarted, /Open offer doc/);
  assert.match(gettingStarted, /Open demo script/);
  assert.match(gettingStarted, /Open outreach list/);
  assert.match(gettingStarted, /Open pilot scorecard/);
  assert.match(gettingStarted, /docs\/local-services-pilot-runbook\.md/);
  assert.match(gettingStarted, /Playbook templates/);
  assert.match(gettingStarted, /Each card previews `Outcome`, `Approval`, `Evidence`, and `Deliverable`/);
  assert.match(gettingStarted, /Selecting a card opens the inline detail panel with `Sample input`, `Approval policy`,\s+`Evidence output`, and `CRM fields`/);
  assert.match(gettingStarted, /`Payload preview`, `Surface path`, and `Copy payload`/);
  assert.match(gettingStarted, /Open export drawer/);
  assert.match(gettingStarted, /Human-readable` and `JSON`/);
  assert.match(gettingStarted, /Case Outcome Summary/);
  assert.match(localServicesSpec, /AI Dispatcher for local service businesses/);
  assert.match(localServicesSpec, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(localServicesSpec, /Measurement visit booking/);
  assert.match(localServicesSpec, /measurement visits for windows, doors, ceilings, blinds, and fit-out work/);
  assert.match(localServicesSpec, /Dispatch payload drawer/);
  assert.match(localServicesSpec, /Customer confirmation drawer/);
  assert.match(localServicesSpec, /Master\/operator handoff drawer/);
  assert.match(localServicesSpec, /Telegram intake prototype/);
  assert.match(localServicesSpec, /Pilot readiness/);
  assert.match(localServicesSpec, /One-page offer/);
  assert.match(localServicesSpec, /90-second demo script/);
  assert.match(localServicesSpec, /Launch checklist/);
  assert.match(localServicesSpec, /Pilot metrics/);
  assert.match(localServicesSpec, /Pilot outreach wizard/);
  assert.match(localServicesSpec, /Audience from outreach list/);
  assert.match(localServicesSpec, /Test message preview/);
  assert.match(localServicesSpec, /Operator confirmation/);
  assert.match(localServicesSpec, /Pilot scorecard action/);
  assert.match(localServicesSpec, /Record scorecard draft/);
  assert.match(localServicesSpec, /Not contacted/);
  assert.match(localServicesSpec, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(localServicesSpec, /Draft ready/);
  assert.match(localServicesSpec, /Contacted manually/);
  assert.match(localServicesSpec, /Reply received/);
  assert.match(localServicesSpec, /Rejected for now/);
  assert.match(localServicesSpec, /Saved in this browser/);
  assert.match(localServicesSpec, /Pilot funnel summary/);
  assert.match(localServicesSpec, /All candidates/);
  assert.match(localServicesSpec, /Next manual batch/);
  assert.match(localServicesSpec, /Manual execution rule/);
  assert.match(localServicesSpec, /Open pilot export/);
  assert.match(localServicesSpec, /Pilot workspace export drawer/);
  assert.match(localServicesSpec, /Copy pilot workspace export/);
  assert.match(localServicesSpec, /Pilot metrics tracker/);
  assert.match(localServicesSpec, /Copy pilot metrics tracker/);
  assert.match(localServicesSpec, /No outbound message sent/);
  assert.match(localServicesSpec, /no real\s+outreach is sent autonomously/);
  assert.match(localServicesSpec, /\/workspace-docs\/local-services-pilot-offer\.md/);
  assert.match(localServicesSpec, /\/workspace-docs\/local-services-demo-script\.md/);
  assert.match(localServicesSpec, /\/workspace-docs\/local-services-outreach-list\.md/);
  assert.match(localServicesSpec, /\/workspace-docs\/local-services-pilot-scorecard\.md/);
  assert.match(localServicesSpec, /\/workspace-docs\/local-services-pilot-runbook\.md/);
  assert.match(localServicesSpec, /Actual external execution still remains outside the shell/);
  assert.match(localServicesSpec, /same approval-gated job-card payload/);
  assert.match(localServicesSpec, /operator-approved action/);

  assert.match(pilotOffer, /# Local Services Pilot Offer/);
  assert.match(pilotOffer, /AI Dispatcher for Local Services/);
  assert.match(pilotOffer, /measurement visits/);
  assert.match(pilotOffer, /construction-material stock or delivery automation/);
  assert.match(pilotOffer, /Day-One Setup/);
  assert.match(pilotOffer, /Success Criteria For 14 Days/);
  assert.match(demoScript, /# Local Services 90-Second Demo Script/);
  assert.match(demoScript, /\/app\?demo=local-services-dispatch&service=ac-repair-dispatch/);
  assert.match(demoScript, /Pilot readiness/);
  assert.match(demoScript, /Open metrics tracker/);
  assert.match(demoScript, /Measurement visit booking/);
  assert.match(demoScript, /final pricing are not automated in P0/);
  assert.match(demoScript, /operator-approved dispatch/);
  assert.match(outreachList, /# Local Services Outreach List/);
  assert.match(outreachList, /Checked against public sources on 2026-04-26/);
  assert.match(outreachList, /AC MASTER/);
  assert.match(outreachList, /Santexniki\.uz/);
  assert.match(outreachList, /Service-Pro/);
  assert.match(outreachList, /IMZO/);
  assert.match(outreachList, /Modern Systems/);
  assert.match(outreachList, /BRIX\.UZ/);
  assert.match(outreachList, /Scorecard draft/);
  assert.match(outreachList, /Not contacted/);
  assert.match(outreachList, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(outreachList, /Pilot funnel summary/);
  assert.match(outreachList, /Next manual batch/);
  assert.match(outreachList, /Benchmarks, Not First Calls/);
  assert.match(pilotScorecard, /# Local Services Pilot Scorecard/);
  assert.match(pilotScorecard, /Account Qualification Score/);
  assert.match(pilotScorecard, /Measurement or media intake/);
  assert.match(pilotScorecard, /14-18/);
  assert.match(pilotScorecard, /Shell Draft Flow/);
  assert.match(pilotScorecard, /Pilot scorecard action/);
  assert.match(pilotScorecard, /Record scorecard draft/);
  assert.match(pilotScorecard, /liveDesk:localServicesPilotWorkspace:v1/);
  assert.match(pilotScorecard, /Draft ready/);
  assert.match(pilotScorecard, /Contacted manually/);
  assert.match(pilotScorecard, /Reply received/);
  assert.match(pilotScorecard, /Rejected for now/);
  assert.match(pilotScorecard, /Pilot funnel summary/);
  assert.match(pilotScorecard, /All candidates/);
  assert.match(pilotScorecard, /Next manual batch/);
  assert.match(pilotScorecard, /manual execution rule/);
  assert.match(pilotScorecard, /Open pilot export/);
  assert.match(pilotScorecard, /Pilot workspace export drawer/);
  assert.match(pilotScorecard, /Copy pilot workspace export/);
  assert.match(pilotScorecard, /Pilot metrics tracker/);
  assert.match(pilotScorecard, /Copy pilot metrics tracker/);
  assert.match(pilotScorecard, /does not send a\s+message/);
  assert.match(pilotScorecard, /14-Day Pilot Scorecard/);
  assert.match(pilotScorecard, /Pilot Exit Rules/);
  assert.match(pilotScorecard, /docs\/local-services-pilot-runbook\.md/);
  assert.match(pilotRunbook, /# Local Services Pilot Runbook/);
  assert.match(pilotRunbook, /Day Minus One: Prepare/);
  assert.match(pilotRunbook, /Day Zero: Outreach/);
  assert.match(pilotRunbook, /Discovery Call/);
  assert.match(pilotRunbook, /Pilot Setup/);
  assert.match(pilotRunbook, /Daily Operating Loop/);
  assert.match(pilotRunbook, /Week One Review/);
  assert.match(pilotRunbook, /Week Two Review/);
  assert.match(pilotRunbook, /Evidence Pack/);
  assert.match(pilotRunbook, /The shell must not send messages/);
  assert.match(pilotRunbook, /Do not store private customer data in public docs/);
});

test("simulation lab prefers runtime governance metadata for the live policy snapshot", () => {
  const workspaceRuntime = readAppShellSource("hooks/useWorkspaceRuntime.tsx");
  const runtimePolicies = readAppShellSource("lib/runtime-simulation-policies.ts");
  const simulationLab = readAppShellSource("components/workspace/SimulationLab.tsx");
  const newReplaySheet = readAppShellSource("components/workspace/NewReplaySheet.tsx");
  const runDetailDrawer = readAppShellSource("components/workspace/RunDetailDrawer.tsx");
  const policyBlurb = readAppShellSource("components/workspace/runDetail/PolicyBlurb.tsx");
  const readme = readRepoSource("README.md");
  const operatorGuide = readRepoSource("docs/operator-guide.md");

  assert.match(workspaceRuntime, /governancePolicy: RuntimeGovernancePolicy \| null;/);
  assert.match(workspaceRuntime, /governanceTemplateCatalog: RuntimeGovernanceTemplateCatalog \| null;/);
  assert.match(workspaceRuntime, /governancePolicyUpdates: RuntimeGovernancePolicyUpdate\[\];/);
  assert.match(workspaceRuntime, /promoteGovernancePolicyTemplate: \(/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/governance\/policy"/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/governance\/compliance-template"/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*`\/v1\/governance\/policy\/\$\{encodeURIComponent\(tenantId\)\}\/updates\?limit=12`/);
  assert.match(workspaceRuntime, /fetchRuntimeApi\(\s*"\/v1\/governance\/policy",\s*\{\s*method: "POST"/);
  assert.match(workspaceRuntime, /"x-operator-role": "admin"/);

  assert.match(runtimePolicies, /export function buildSimulationPolicySnapshots/);
  assert.match(runtimePolicies, /const TEMPLATE_POLICY_PREFIX = "policy-template-";/);
  assert.match(runtimePolicies, /function buildRuntimeTemplatePolicyId/);
  assert.match(runtimePolicies, /Template \$\{template\} from \$\{source\}/);
  assert.match(runtimePolicies, /Promote to live to apply it to the operator desk/i);

  assert.match(simulationLab, /governanceTemplateCatalog,/);
  assert.match(simulationLab, /governancePolicyUpdates,/);
  assert.match(simulationLab, /buildSimulationPolicySnapshots\(\s*governancePolicy,\s*governanceTemplateCatalog,\s*governancePolicyUpdates,\s*\)/);
  assert.match(simulationLab, /buildRuntimeSimulationRuns\(cases, policies\)/);
  assert.match(simulationLab, /findCase,/);
  assert.match(simulationLab, /const c = findCase\(run\.caseRef\);/);
  assert.match(newReplaySheet, /policies: PolicySnapshot\[\];/);
  assert.match(newReplaySheet, /policies\.find\(\(policy\) => policy\.id === policyId\)/);
  assert.match(runDetailDrawer, /policies: PolicySnapshot\[\];/);
  assert.match(runDetailDrawer, /findSimulationPolicy\(run\.policyId, policies\)/);
  assert.match(runDetailDrawer, /promoteGovernancePolicyTemplate/);
  assert.match(runDetailDrawer, /Live policy updated to/);
  assert.match(policyBlurb, /policy: PolicySnapshot \| null \| undefined/);
  assert.match(policyBlurb, /Recent governance activity/);

  assert.match(readme, /Simulation Lab` now also overlays the live `policy-current` snapshot/i);
  assert.match(readme, /repo-owned governance runtime data \(`\/v1\/governance\/policy`\)/i);
  assert.match(readme, /`\/v1\/governance\/compliance-template`/i);
  assert.match(readme, /`POST \/v1\/governance\/policy`/i);
  assert.match(operatorGuide, /Simulation Lab policy note:/);
});
