import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("gateway exposes public demo badge endpoints", () => {
  const gatewaySource = readFileSync(
    resolve(process.cwd(), "apps", "realtime-gateway", "src", "index.ts"),
    "utf8",
  );

  assert.match(gatewaySource, /\/demo-e2e\/badge\.json/);
  assert.match(gatewaySource, /\/demo-e2e\/badge-details\.json/);
  assert.match(gatewaySource, /public, max-age=300/);
  assert.match(gatewaySource, /public, max-age=60/);
});

test("tracked public badge payload has required schema fields", () => {
  const badgePath = resolve(process.cwd(), "public", "demo-e2e", "badge.json");
  const badge = JSON.parse(readFileSync(badgePath, "utf8")) as Record<string, unknown>;

  assert.equal(badge.schemaVersion, 1);
  assert.equal(typeof badge.label, "string");
  assert.equal(typeof badge.message, "string");
  assert.equal(typeof badge.color, "string");
  assert.equal(typeof badge.cacheSeconds, "number");
});

test("tracked public badge details embed badge payload", () => {
  const detailsPath = resolve(process.cwd(), "public", "demo-e2e", "badge-details.json");
  const details = JSON.parse(readFileSync(detailsPath, "utf8")) as Record<string, unknown>;
  const badge = details.badge as Record<string, unknown>;
  const evidence = details.evidence as Record<string, unknown>;
  assert.ok(evidence && typeof evidence === "object");
  const turnTruncation = evidence.operatorTurnTruncation as Record<string, unknown>;
  const turnDelete = evidence.operatorTurnDelete as Record<string, unknown>;
  const damageControl = evidence.damageControl as Record<string, unknown>;
  const operatorDamageControl = evidence.operatorDamageControl as Record<string, unknown>;
  const governancePolicy = evidence.governancePolicy as Record<string, unknown>;
  const skillsRegistry = evidence.skillsRegistry as Record<string, unknown>;
  const deviceNodes = evidence.deviceNodes as Record<string, unknown>;
  assert.ok(turnTruncation && typeof turnTruncation === "object");
  assert.ok(turnDelete && typeof turnDelete === "object");
  assert.ok(damageControl && typeof damageControl === "object");
  assert.ok(operatorDamageControl && typeof operatorDamageControl === "object");
  assert.ok(governancePolicy && typeof governancePolicy === "object");
  assert.ok(skillsRegistry && typeof skillsRegistry === "object");
  assert.ok(deviceNodes && typeof deviceNodes === "object");

  assert.equal(details.ok, true);
  assert.equal(typeof details.generatedAt, "string");
  assert.equal(typeof details.checks, "number");
  assert.equal(typeof details.violations, "number");
  assert.equal(typeof details.roundTripMs, "number");
  assert.equal(typeof details.costEstimate, "object");
  assert.equal(typeof details.tokensUsed, "object");
  assert.equal(typeof details.evidence, "object");
  const costEstimate = details.costEstimate as Record<string, unknown>;
  const tokensUsed = details.tokensUsed as Record<string, unknown>;
  assert.ok(costEstimate && typeof costEstimate === "object");
  assert.ok(tokensUsed && typeof tokensUsed === "object");
  assert.equal(typeof costEstimate.currency, "string");
  assert.equal(typeof costEstimate.geminiLiveUsd, "number");
  assert.equal(typeof costEstimate.imagenUsd, "number");
  assert.equal(typeof costEstimate.veoUsd, "number");
  assert.equal(typeof costEstimate.ttsUsd, "number");
  assert.equal(typeof costEstimate.totalUsd, "number");
  assert.equal(typeof costEstimate.source, "string");
  assert.equal(typeof tokensUsed.input, "number");
  assert.equal(typeof tokensUsed.output, "number");
  assert.equal(typeof tokensUsed.total, "number");
  assert.equal(typeof tokensUsed.source, "string");
  assert.equal(typeof turnTruncation.status, "string");
  assert.equal(typeof turnDelete.status, "string");
  assert.equal(typeof turnTruncation.validated, "boolean");
  assert.equal(typeof turnDelete.validated, "boolean");
  assert.equal(typeof turnTruncation.total, "number");
  assert.equal(typeof turnDelete.total, "number");
  assert.equal(typeof turnTruncation.latestSeenAtIsIso, "boolean");
  assert.equal(typeof turnDelete.latestSeenAtIsIso, "boolean");
  assert.equal(typeof damageControl.status, "string");
  assert.equal(typeof damageControl.diagnosticsValidated, "boolean");
  assert.equal(typeof damageControl.enabled, "boolean");
  assert.equal(typeof damageControl.matchedRuleCount, "number");
  assert.equal(Array.isArray(damageControl.matchedRuleIds), true);
  assert.equal(typeof operatorDamageControl.status, "string");
  assert.equal(typeof operatorDamageControl.validated, "boolean");
  assert.equal(typeof operatorDamageControl.total, "number");
  assert.equal(typeof operatorDamageControl.uniqueRuns, "number");
  assert.equal(typeof operatorDamageControl.uniqueSessions, "number");
  assert.equal(typeof operatorDamageControl.matchedRuleCountTotal, "number");
  const operatorDamageControlVerdictCounts = operatorDamageControl.verdictCounts as Record<string, unknown>;
  const operatorDamageControlLatest = operatorDamageControl.latest as Record<string, unknown>;
  assert.ok(operatorDamageControlVerdictCounts && typeof operatorDamageControlVerdictCounts === "object");
  assert.ok(operatorDamageControlLatest && typeof operatorDamageControlLatest === "object");
  assert.equal(typeof operatorDamageControlVerdictCounts.allow, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.ask, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.block, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.total, "number");
  assert.equal(typeof operatorDamageControlLatest.verdict, "string");
  assert.equal(typeof operatorDamageControlLatest.source, "string");
  assert.equal(typeof operatorDamageControlLatest.matchedRuleCount, "number");
  assert.equal(typeof operatorDamageControlLatest.seenAt, "string");
  assert.equal(typeof operatorDamageControlLatest.seenAtIsIso, "boolean");
  assert.equal(typeof governancePolicy.status, "string");
  assert.equal(typeof governancePolicy.validated, "boolean");
  assert.equal(typeof governancePolicy.operatorActionSeen, "boolean");
  assert.equal(typeof governancePolicy.overrideTenantSeen, "boolean");
  assert.equal(typeof governancePolicy.idempotencyReplayOutcome, "string");
  assert.equal(typeof governancePolicy.versionConflictCode, "string");
  assert.equal(typeof governancePolicy.idempotencyConflictCode, "string");
  assert.equal(typeof governancePolicy.tenantScopeForbiddenCode, "string");
  assert.equal(typeof governancePolicy.summaryTemplateId, "string");
  assert.equal(typeof governancePolicy.summarySource, "string");
  assert.equal(typeof governancePolicy.complianceTemplate, "string");
  assert.equal(typeof governancePolicy.overridesTotal, "number");
  assert.equal(typeof skillsRegistry.status, "string");
  assert.equal(typeof skillsRegistry.validated, "boolean");
  assert.equal(typeof skillsRegistry.indexHasSkill, "boolean");
  assert.equal(typeof skillsRegistry.registryHasSkill, "boolean");
  assert.equal(typeof skillsRegistry.createOutcome, "string");
  assert.equal(typeof skillsRegistry.replayOutcome, "string");
  assert.equal(typeof skillsRegistry.versionConflictCode, "string");
  assert.equal(typeof skillsRegistry.pluginInvalidPermissionCode, "string");
  assert.equal(typeof skillsRegistry.indexTotal, "number");
  assert.equal(typeof skillsRegistry.registryTotal, "number");
  assert.equal(typeof deviceNodes.status, "string");
  assert.equal(typeof deviceNodes.validated, "boolean");
  assert.equal(typeof deviceNodes.lookupValidated, "boolean");
  assert.equal(typeof deviceNodes.versionConflictValidated, "boolean");
  assert.equal(typeof deviceNodes.healthSummaryValidated, "boolean");
  assert.equal(typeof deviceNodes.lookupStatus, "string");
  assert.equal(typeof deviceNodes.lookupVersion, "number");
  assert.equal(typeof deviceNodes.updatedVersion, "number");
  assert.equal(typeof deviceNodes.versionConflictStatusCode, "number");
  assert.equal(typeof deviceNodes.versionConflictCode, "string");
  assert.equal(typeof deviceNodes.summaryTotal, "number");
  assert.equal(typeof deviceNodes.summaryDegraded, "number");
  assert.equal(typeof deviceNodes.summaryStale, "number");
  assert.equal(typeof deviceNodes.summaryMissingHeartbeat, "number");
  assert.equal(typeof deviceNodes.summaryRecentContainsLookup, "boolean");
  assert.equal(typeof details.policyPath, "string");
  assert.equal(typeof details.summaryPath, "string");
  assert.equal(badge.schemaVersion, 1);
  assert.equal(typeof badge.label, "string");
  assert.equal(typeof badge.message, "string");
  assert.equal(typeof badge.color, "string");
  assert.equal(typeof badge.cacheSeconds, "number");
});
