import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("gateway exposes public demo badge endpoints", () => {
  const gatewaySource = readFileSync(
    resolve(process.cwd(), "apps", "realtime-gateway", "src", "index.ts"),
    "utf8",
  );

  assert.match(gatewaySource, /\/demo-e2e\/badge\.json/);
  assert.match(gatewaySource, /\/demo-e2e\/badge-details\.json/);
  assert.match(gatewaySource, /public, max-age=300/);
  assert.match(gatewaySource, /public, max-age=60/);
});

test("tracked public badge payload has required schema fields", () => {
  const badgePath = resolve(process.cwd(), "public", "demo-e2e", "badge.json");
  const badge = JSON.parse(readFileSync(badgePath, "utf8")) as Record<string, unknown>;

  assert.equal(badge.schemaVersion, 1);
  assert.equal(typeof badge.label, "string");
  assert.equal(typeof badge.message, "string");
  assert.equal(typeof badge.color, "string");
  assert.equal(typeof badge.cacheSeconds, "number");
});

test("tracked public badge details embed badge payload", () => {
  const detailsPath = resolve(process.cwd(), "public", "demo-e2e", "badge-details.json");
  const details = JSON.parse(readFileSync(detailsPath, "utf8")) as Record<string, unknown>;
  const badge = details.badge as Record<string, unknown>;
  const evidence = details.evidence as Record<string, unknown>;
  assert.ok(evidence && typeof evidence === "object");
  const turnTruncation = evidence.operatorTurnTruncation as Record<string, unknown>;
  const turnDelete = evidence.operatorTurnDelete as Record<string, unknown>;
  const damageControl = evidence.damageControl as Record<string, unknown>;
  const operatorDamageControl = evidence.operatorDamageControl as Record<string, unknown>;
  const governancePolicy = evidence.governancePolicy as Record<string, unknown>;
  const skillsRegistry = evidence.skillsRegistry as Record<string, unknown>;
  const pluginMarketplace = evidence.pluginMarketplace as Record<string, unknown>;
  const deviceNodes = evidence.deviceNodes as Record<string, unknown>;
  const agentUsage = evidence.agentUsage as Record<string, unknown>;
  const runtimeGuardrailsSignalPaths = evidence.runtimeGuardrailsSignalPaths as Record<string, unknown>;
  const providerUsage = details.providerUsage as Record<string, unknown>;
  assert.ok(turnTruncation && typeof turnTruncation === "object");
  assert.ok(turnDelete && typeof turnDelete === "object");
  assert.ok(damageControl && typeof damageControl === "object");
  assert.ok(operatorDamageControl && typeof operatorDamageControl === "object");
  assert.ok(governancePolicy && typeof governancePolicy === "object");
  assert.ok(skillsRegistry && typeof skillsRegistry === "object");
  assert.ok(pluginMarketplace && typeof pluginMarketplace === "object");
  assert.ok(deviceNodes && typeof deviceNodes === "object");
  assert.ok(agentUsage && typeof agentUsage === "object");
  assert.ok(runtimeGuardrailsSignalPaths && typeof runtimeGuardrailsSignalPaths === "object");
  assert.ok(providerUsage && typeof providerUsage === "object");

  assert.equal(details.ok, true);
  assert.equal(typeof details.generatedAt, "string");
  assert.equal(typeof details.checks, "number");
  assert.equal(typeof details.violations, "number");
  assert.equal(typeof details.roundTripMs, "number");
  assert.equal(typeof details.costEstimate, "object");
  assert.equal(typeof details.tokensUsed, "object");
  assert.equal(typeof details.evidence, "object");
  const costEstimate = details.costEstimate as Record<string, unknown>;
  const tokensUsed = details.tokensUsed as Record<string, unknown>;
  assert.ok(costEstimate && typeof costEstimate === "object");
  assert.ok(tokensUsed && typeof tokensUsed === "object");
  assert.equal(typeof costEstimate.currency, "string");
  assert.equal(typeof costEstimate.geminiLiveUsd, "number");
  assert.equal(typeof costEstimate.imagenUsd, "number");
  assert.equal(typeof costEstimate.veoUsd, "number");
  assert.equal(typeof costEstimate.ttsUsd, "number");
  assert.equal(typeof costEstimate.totalUsd, "number");
  assert.equal(typeof costEstimate.source, "string");
  assert.equal(typeof tokensUsed.input, "number");
  assert.equal(typeof tokensUsed.output, "number");
  assert.equal(typeof tokensUsed.total, "number");
  assert.equal(typeof tokensUsed.source, "string");
  assert.equal(typeof providerUsage.status, "string");
  assert.equal(typeof providerUsage.validated, "boolean");
  assert.equal(typeof providerUsage.activeSecondaryProviders, "number");
  assert.equal(Array.isArray(providerUsage.entries), true);
  const providerUsageEntries = providerUsage.entries as Record<string, unknown>[];
  assert.ok(providerUsageEntries.length >= 1);
  assert.equal(typeof providerUsageEntries[0]?.route, "string");
  assert.equal(typeof providerUsageEntries[0]?.capability, "string");
  assert.equal(typeof providerUsageEntries[0]?.selectedProvider, "string");
  assert.equal(typeof providerUsageEntries[0]?.selectedModel, "string");
  assert.equal(typeof providerUsageEntries[0]?.selectionReason, "string");
  assert.equal(typeof turnTruncation.status, "string");
  assert.equal(typeof turnDelete.status, "string");
  assert.equal(typeof turnTruncation.validated, "boolean");
  assert.equal(typeof turnDelete.validated, "boolean");
  assert.equal(typeof turnTruncation.total, "number");
  assert.equal(typeof turnDelete.total, "number");
  assert.equal(typeof turnTruncation.latestSeenAtIsIso, "boolean");
  assert.equal(typeof turnDelete.latestSeenAtIsIso, "boolean");
  assert.equal(typeof damageControl.status, "string");
  assert.equal(typeof damageControl.diagnosticsValidated, "boolean");
  assert.equal(typeof damageControl.enabled, "boolean");
  assert.equal(typeof damageControl.matchedRuleCount, "number");
  assert.equal(Array.isArray(damageControl.matchedRuleIds), true);
  assert.equal(typeof operatorDamageControl.status, "string");
  assert.equal(typeof operatorDamageControl.validated, "boolean");
  assert.equal(typeof operatorDamageControl.total, "number");
  assert.equal(typeof operatorDamageControl.uniqueRuns, "number");
  assert.equal(typeof operatorDamageControl.uniqueSessions, "number");
  assert.equal(typeof operatorDamageControl.matchedRuleCountTotal, "number");
  const operatorDamageControlVerdictCounts = operatorDamageControl.verdictCounts as Record<string, unknown>;
  const operatorDamageControlLatest = operatorDamageControl.latest as Record<string, unknown>;
  assert.ok(operatorDamageControlVerdictCounts && typeof operatorDamageControlVerdictCounts === "object");
  assert.ok(operatorDamageControlLatest && typeof operatorDamageControlLatest === "object");
  assert.equal(typeof operatorDamageControlVerdictCounts.allow, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.ask, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.block, "number");
  assert.equal(typeof operatorDamageControlVerdictCounts.total, "number");
  assert.equal(typeof operatorDamageControlLatest.verdict, "string");
  assert.equal(typeof operatorDamageControlLatest.source, "string");
  assert.equal(typeof operatorDamageControlLatest.matchedRuleCount, "number");
  assert.equal(typeof operatorDamageControlLatest.seenAt, "string");
  assert.equal(typeof operatorDamageControlLatest.seenAtIsIso, "boolean");
  assert.equal(typeof governancePolicy.status, "string");
  assert.equal(typeof governancePolicy.validated, "boolean");
  assert.equal(typeof governancePolicy.operatorActionSeen, "boolean");
  assert.equal(typeof governancePolicy.overrideTenantSeen, "boolean");
  assert.equal(typeof governancePolicy.idempotencyReplayOutcome, "string");
  assert.equal(typeof governancePolicy.versionConflictCode, "string");
  assert.equal(typeof governancePolicy.idempotencyConflictCode, "string");
  assert.equal(typeof governancePolicy.tenantScopeForbiddenCode, "string");
  assert.equal(typeof governancePolicy.summaryTemplateId, "string");
  assert.equal(typeof governancePolicy.summarySource, "string");
  assert.equal(typeof governancePolicy.complianceTemplate, "string");
  assert.equal(typeof governancePolicy.overridesTotal, "number");
  assert.equal(typeof skillsRegistry.status, "string");
  assert.equal(typeof skillsRegistry.validated, "boolean");
  assert.equal(typeof skillsRegistry.indexHasSkill, "boolean");
  assert.equal(typeof skillsRegistry.registryHasSkill, "boolean");
  assert.equal(typeof skillsRegistry.createOutcome, "string");
  assert.equal(typeof skillsRegistry.replayOutcome, "string");
  assert.equal(typeof skillsRegistry.versionConflictCode, "string");
  assert.equal(typeof skillsRegistry.pluginInvalidPermissionCode, "string");
  assert.equal(typeof skillsRegistry.indexTotal, "number");
  assert.equal(typeof skillsRegistry.registryTotal, "number");
  assert.equal(typeof pluginMarketplace.status, "string");
  assert.equal(typeof pluginMarketplace.validated, "boolean");
  assert.equal(typeof pluginMarketplace.summaryStatus, "string");
  assert.equal(typeof pluginMarketplace.total, "number");
  assert.equal(typeof pluginMarketplace.uniquePlugins, "number");
  const pluginMarketplaceOutcomes = pluginMarketplace.outcomes as Record<string, unknown>;
  const pluginMarketplaceLifecycle = pluginMarketplace.lifecycle as Record<string, unknown>;
  const pluginMarketplaceConflicts = pluginMarketplace.conflicts as Record<string, unknown>;
  const pluginMarketplaceSigningStatusCounts = pluginMarketplace.signingStatusCounts as Record<string, unknown>;
  const pluginMarketplacePermissionTotals = pluginMarketplace.permissionTotals as Record<string, unknown>;
  const pluginMarketplaceLatest = pluginMarketplace.latest as Record<string, unknown>;
  assert.ok(pluginMarketplaceOutcomes && typeof pluginMarketplaceOutcomes === "object");
  assert.ok(pluginMarketplaceLifecycle && typeof pluginMarketplaceLifecycle === "object");
  assert.ok(pluginMarketplaceConflicts && typeof pluginMarketplaceConflicts === "object");
  assert.ok(pluginMarketplaceSigningStatusCounts && typeof pluginMarketplaceSigningStatusCounts === "object");
  assert.ok(pluginMarketplacePermissionTotals && typeof pluginMarketplacePermissionTotals === "object");
  assert.ok(pluginMarketplaceLatest && typeof pluginMarketplaceLatest === "object");
  assert.equal(typeof pluginMarketplaceOutcomes.succeeded, "number");
  assert.equal(typeof pluginMarketplaceOutcomes.denied, "number");
  assert.equal(typeof pluginMarketplaceOutcomes.failed, "number");
  assert.equal(typeof pluginMarketplaceOutcomes.total, "number");
  assert.equal(typeof pluginMarketplaceLifecycle.created, "number");
  assert.equal(typeof pluginMarketplaceLifecycle.updated, "number");
  assert.equal(typeof pluginMarketplaceLifecycle.idempotentReplay, "number");
  assert.equal(typeof pluginMarketplaceConflicts.versionConflict, "number");
  assert.equal(typeof pluginMarketplaceConflicts.pluginInvalidPermission, "number");
  assert.equal(typeof pluginMarketplaceSigningStatusCounts.verified, "number");
  assert.equal(typeof pluginMarketplaceSigningStatusCounts.unsigned, "number");
  assert.equal(typeof pluginMarketplaceSigningStatusCounts.none, "number");
  assert.equal(typeof pluginMarketplaceSigningStatusCounts.total, "number");
  assert.equal(typeof pluginMarketplace.signingEvidenceObserved, "boolean");
  assert.equal(typeof pluginMarketplacePermissionTotals.totalPermissions, "number");
  assert.equal(typeof pluginMarketplacePermissionTotals.entriesWithPermissions, "number");
  assert.equal(typeof pluginMarketplaceLatest.outcome, "string");
  assert.equal(typeof pluginMarketplaceLatest.pluginId, "string");
  assert.equal(typeof pluginMarketplaceLatest.version, "number");
  assert.equal(typeof pluginMarketplaceLatest.signingStatus, "string");
  assert.equal(typeof pluginMarketplaceLatest.seenAt, "string");
  assert.equal(typeof pluginMarketplaceLatest.seenAtIsIso, "boolean");
  assert.equal(typeof deviceNodes.status, "string");
  assert.equal(typeof deviceNodes.validated, "boolean");
  assert.equal(typeof deviceNodes.lookupValidated, "boolean");
  assert.equal(typeof deviceNodes.versionConflictValidated, "boolean");
  assert.equal(typeof deviceNodes.healthSummaryValidated, "boolean");
  assert.equal(typeof deviceNodes.lookupStatus, "string");
  assert.equal(typeof deviceNodes.lookupVersion, "number");
  assert.equal(typeof deviceNodes.updatedVersion, "number");
  assert.equal(typeof deviceNodes.versionConflictStatusCode, "number");
  assert.equal(typeof deviceNodes.versionConflictCode, "string");
  assert.equal(typeof deviceNodes.summaryTotal, "number");
  assert.equal(typeof deviceNodes.summaryDegraded, "number");
  assert.equal(typeof deviceNodes.summaryStale, "number");
  assert.equal(typeof deviceNodes.summaryMissingHeartbeat, "number");
  assert.equal(typeof deviceNodes.summaryRecentContainsLookup, "boolean");
  assert.equal(typeof agentUsage.status, "string");
  assert.equal(typeof agentUsage.validated, "boolean");
  assert.equal(typeof agentUsage.total, "number");
  assert.equal(typeof agentUsage.uniqueRuns, "number");
  assert.equal(typeof agentUsage.uniqueSessions, "number");
  assert.equal(typeof agentUsage.totalCalls, "number");
  assert.equal(typeof agentUsage.inputTokens, "number");
  assert.equal(typeof agentUsage.outputTokens, "number");
  assert.equal(typeof agentUsage.totalTokens, "number");
  assert.equal(Array.isArray(agentUsage.models), true);
  assert.equal(typeof agentUsage.summarySource, "string");
  assert.equal(typeof agentUsage.summaryStatus, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.status, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.validated, "boolean");
  assert.equal(typeof runtimeGuardrailsSignalPaths.summaryStatus, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.signalsSummary, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.coverageSummary, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.sandboxSummary, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.skillsSummary, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.topSignal, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.historyStatus, "string");
  assert.equal(typeof runtimeGuardrailsSignalPaths.totalPaths, "number");
  assert.equal(typeof runtimeGuardrailsSignalPaths.lifecycleSummary, "string");
  assert.equal(Array.isArray(runtimeGuardrailsSignalPaths.paths), true);
  const runtimeGuardrailsLifecycleCounts = runtimeGuardrailsSignalPaths.lifecycleCounts as Record<string, unknown>;
  assert.ok(runtimeGuardrailsLifecycleCounts && typeof runtimeGuardrailsLifecycleCounts === "object");
  assert.equal(typeof runtimeGuardrailsLifecycleCounts.active, "number");
  assert.equal(typeof runtimeGuardrailsLifecycleCounts.failed, "number");
  const runtimeGuardrailsPrimaryPath = runtimeGuardrailsSignalPaths.primaryPath as Record<string, unknown> | null;
  if ((runtimeGuardrailsSignalPaths.totalPaths as number) > 0) {
    assert.ok(runtimeGuardrailsPrimaryPath && typeof runtimeGuardrailsPrimaryPath === "object");
    assert.equal(typeof runtimeGuardrailsPrimaryPath.title, "string");
    assert.equal(typeof runtimeGuardrailsPrimaryPath.kind, "string");
    assert.equal(typeof runtimeGuardrailsPrimaryPath.summaryText, "string");
  }
  assert.equal(typeof details.policyPath, "string");
  assert.equal(typeof details.summaryPath, "string");
  assert.equal(badge.schemaVersion, 1);
  assert.equal(typeof badge.label, "string");
  assert.equal(typeof badge.message, "string");
  assert.equal(typeof badge.color, "string");
  assert.equal(typeof badge.cacheSeconds, "number");
});
