import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("railway deploy helper stays aligned across package, script, and docs", () => {
  const packagePath = resolve(process.cwd(), "package.json");
  const packageRaw = readFileSync(packagePath, "utf8");
  const pkg = JSON.parse(packageRaw) as { scripts?: Record<string, string> };

  const deployAlias = pkg.scripts?.["deploy:railway"] ?? "";
  assert.match(deployAlias, /railway-deploy\.ps1/);

  const scriptPath = resolve(process.cwd(), "scripts/railway-deploy.ps1");
  const scriptRaw = readFileSync(scriptPath, "utf8");
  assert.match(scriptRaw, /\$env:RAILWAY_PROJECT_ID/);
  assert.match(scriptRaw, /\$env:RAILWAY_SERVICE_ID/);
  assert.match(scriptRaw, /SkipReleaseVerification/);
  assert.match(scriptRaw, /StrictReleaseVerification/);
  assert.match(scriptRaw, /SkipPublicBadgeCheck/);
  assert.match(scriptRaw, /PublicBadgeEndpoint/);
  assert.match(scriptRaw, /PublicBadgeDetailsEndpoint/);
  assert.match(scriptRaw, /RailwayPublicUrl/);
  assert.match(scriptRaw, /DemoFrontendPublicUrl/);
  assert.match(scriptRaw, /function Write-GitHubOutputValue\(/);
  assert.match(scriptRaw, /function Write-GitHubStepSummaryLine\(/);
  assert.match(scriptRaw, /function Read-JsonArtifactIfPresent\(/);
  assert.match(scriptRaw, /function Get-CompactRuntimeGuardrailsPrimaryPath\(/);
  assert.match(scriptRaw, /function Get-CompactProviderUsagePrimaryEntry\(/);
  assert.match(scriptRaw, /function Get-ReleaseEvidenceSnapshot\(\[bool\]\$ValidatedInThisRun\)/);
  assert.match(scriptRaw, /function Publish-RailwayDeployOutputs\(/);
  assert.match(scriptRaw, /RootDescriptorCheckMaxAttempts/);
  assert.match(scriptRaw, /RootDescriptorCheckRetryBackoffSec/);
  assert.match(scriptRaw, /Invoke-PublicBadgeCheck/);
  assert.match(scriptRaw, /Resolve-ServiceIdFromStatus/);
  assert.match(scriptRaw, /serviceInstances/);
  assert.match(scriptRaw, /@\("link", "-p"/);
  assert.match(scriptRaw, /@\("up", "-d", "-m"/);
  assert.match(scriptRaw, /deployment", "list"/);
  assert.match(scriptRaw, /\$releaseEvidenceSnapshot = Get-ReleaseEvidenceSnapshot -ValidatedInThisRun \(-not \$SkipReleaseVerification\)/);
  assert.match(scriptRaw, /\$railwayVerificationSummary = \[ordered\]@\{/);
  assert.match(scriptRaw, /releaseEvidenceArtifactsValidated = \$false/);
  assert.match(scriptRaw, /\$railwayVerificationSummary\.script = \$verificationScript/);
  assert.match(scriptRaw, /\$railwayVerificationSummary\.releaseEvidenceArtifactsValidated = \(-not \$SkipReleaseVerification\)/);
  assert.match(scriptRaw, /verification = \$railwayVerificationSummary/);
  assert.match(scriptRaw, /artifacts = \[ordered\]@\{/);
  assert.match(scriptRaw, /releaseEvidenceReportJson = "artifacts\/release-evidence\/report\.json"/);
  assert.match(scriptRaw, /releaseEvidenceManifestJson = "artifacts\/release-evidence\/manifest\.json"/);
  assert.match(scriptRaw, /badgeDetailsJson = "artifacts\/demo-e2e\/badge-details\.json"/);
  assert.match(scriptRaw, /releaseEvidenceSnapshot = \$releaseEvidenceSnapshot/);
  assert.match(scriptRaw, /railway_deploy_verification_script/);
  assert.match(scriptRaw, /railway_deploy_verification_skipped/);
  assert.match(scriptRaw, /railway_deploy_verification_strict/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_validated/);
  assert.match(scriptRaw, /railway_deploy_summary_path/);
  assert.match(scriptRaw, /railway_deploy_status/);
  assert.match(scriptRaw, /railway_deploy_deployment_id/);
  assert.match(scriptRaw, /railway_deploy_effective_public_url/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_snapshot_available/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_missing_required/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_badge_checks/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_runtime_guardrails_summary_status/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_report_path/);
  assert.match(scriptRaw, /railway_deploy_release_evidence_manifest_path/);
  assert.match(scriptRaw, /railway_deploy_badge_details_path/);
  assert.match(scriptRaw, /Railway deploy summary artifact:/);
  assert.match(scriptRaw, /Railway deploy verification script:/);
  assert.match(scriptRaw, /Railway deploy verification skipped:/);
  assert.match(scriptRaw, /Railway deploy verification strict:/);
  assert.match(scriptRaw, /Railway deploy release-evidence validated:/);
  assert.match(scriptRaw, /Railway deploy release-evidence snapshot available:/);
  assert.match(scriptRaw, /Railway deploy release-evidence report artifact:/);
  assert.match(scriptRaw, /Railway deploy release-evidence manifest artifact:/);
  assert.match(scriptRaw, /Railway deploy badge-details artifact:/);

  const readmePath = resolve(process.cwd(), "README.md");
  const readmeRaw = readFileSync(readmePath, "utf8");
  assert.match(readmeRaw, /## Railway Deploy Automation/);
  assert.match(readmeRaw, /npm run deploy:railway/);
  assert.match(readmeRaw, /-- -SkipReleaseVerification/);
  assert.match(readmeRaw, /-- -DemoFrontendPublicUrl <url>/);
  assert.match(readmeRaw, /-- -RootDescriptorCheckMaxAttempts <n>/);
  assert.match(readmeRaw, /-- -RootDescriptorCheckRetryBackoffSec <n>/);
  assert.match(readmeRaw, /-- -SkipPublicBadgeCheck/);
  assert.match(readmeRaw, /-- -PublicBadgeEndpoint <url>/);
  assert.match(readmeRaw, /-- -NoWait/);

  const runbookPath = resolve(process.cwd(), "docs/challenge-demo-runbook.md");
  const runbookRaw = readFileSync(runbookPath, "utf8");
  assert.match(runbookRaw, /npm run deploy:railway/);
});
