import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("railway deploy-all workflow is wired to combined helper with required secrets and flags", () => {
  const workflowPath = resolve(process.cwd(), ".github", "workflows", "railway-deploy-all.yml");
  const source = readFileSync(workflowPath, "utf8");

  assert.match(source, /name:\s*Railway Deploy All/);
  assert.match(source, /workflow_dispatch:/);
  assert.match(source, /skip_release_verification:/);
  assert.match(source, /gateway_demo_frontend_public_url:/);
  assert.match(source, /frontend_api_base_url:/);
  assert.match(source, /frontend_ws_url:/);
  assert.match(source, /gateway_root_descriptor_check_max_attempts:/);
  assert.match(source, /gateway_root_descriptor_check_retry_backoff_sec:/);
  assert.match(source, /skip_gateway_deploy:/);
  assert.match(source, /skip_frontend_deploy:/);
  assert.match(source, /gateway_skip_root_descriptor_check:/);
  assert.match(source, /gateway_no_wait:/);
  assert.match(source, /frontend_no_wait:/);
  assert.match(source, /frontend_skip_health_check:/);
  assert.match(source, /verify_only_fallback_on_auth_failure:/);

  assert.match(source, /RAILWAY_API_TOKEN:\s*\$\{\{\s*secrets\.RAILWAY_API_TOKEN\s*\}\}/);
  assert.match(source, /RAILWAY_LEGACY_TOKEN:\s*\$\{\{\s*secrets\.RAILWAY_TOKEN\s*\}\}/);
  assert.match(source, /RAILWAY_PROJECT_TOKEN:\s*\$\{\{\s*secrets\.RAILWAY_PROJECT_TOKEN\s*\}\}/);
  assert.match(source, /RAILWAY_PROJECT_ID:\s*\$\{\{\s*secrets\.RAILWAY_PROJECT_ID\s*\}\}/);
  assert.match(source, /RAILWAY_SERVICE_ID:\s*\$\{\{\s*secrets\.RAILWAY_SERVICE_ID\s*\}\}/);
  assert.match(source, /FRONTEND_PUBLIC_URL:\s*\$\{\{\s*vars\.FRONTEND_PUBLIC_URL\s*\}\}/);

  assert.match(source, /- name:\s*Install Railway CLI/);
  assert.match(source, /npm install -g @railway\/cli/);
  assert.match(source, /- name:\s*Validate Railway Secrets/);
  assert.match(source, /Missing required repository secret: RAILWAY_API_TOKEN \(or legacy RAILWAY_TOKEN\)/);
  assert.match(source, /- name:\s*Probe Railway Auth/);
  assert.match(source, /run:\s*railway whoami/);
  assert.match(source, /- name:\s*Run Combined Railway Deploy/);
  assert.match(source, /id:\s*combined_deploy/);
  assert.match(source, /continue-on-error:\s*true/);
  assert.match(source, /\$gatewayDemoFrontendPublicUrl = "\$\{\{\s*inputs\.gateway_demo_frontend_public_url\s*\}\}"\.Trim\(\)/);
  assert.match(source, /\$frontendApiBaseUrl = "\$\{\{\s*inputs\.frontend_api_base_url\s*\}\}"\.Trim\(\)/);
  assert.match(source, /\$frontendWsUrl = "\$\{\{\s*inputs\.frontend_ws_url\s*\}\}"\.Trim\(\)/);
  assert.match(source, /if \(\[string\]::IsNullOrWhiteSpace\(\$gatewayDemoFrontendPublicUrl\) -and -not \[string\]::IsNullOrWhiteSpace\(\$env:FRONTEND_PUBLIC_URL\)\)/);
  assert.match(source, /-FrontendApiBaseUrl/);
  assert.match(source, /-FrontendWsUrl/);
  assert.match(source, /& powershell -NoProfile -ExecutionPolicy Bypass -File \.\/scripts\/railway-deploy-all\.ps1 @args/);
  assert.match(source, /- name:\s*Verify Public Endpoints Fallback \(Deploy Failure\)/);
  assert.match(source, /id:\s*verify_only_fallback/);
  assert.match(source, /if:\s*steps\.combined_deploy\.outcome != 'success' && inputs\.verify_only_fallback_on_auth_failure == true/);
  assert.match(source, /npm run badge:public:check -- -RailwayPublicUrl/);
  assert.match(source, /frontend fallback health check/i);
  assert.match(source, /- name:\s*Fail on Railway Deploy/);
  assert.match(source, /verify_only_fallback_on_auth_failure=false/);
  assert.match(source, /- name:\s*Run Production Smoke/);
  assert.match(source, /if:\s*steps\.combined_deploy\.outcome == 'success' \|\| steps\.verify_only_fallback\.outcome == 'success'/);
  assert.match(source, /npm run verify:deploy:production-smoke -- -GatewayPublicUrl/);
  assert.match(source, /- name:\s*Install Playwright Browser/);
  assert.match(source, /run:\s*npx playwright install chromium/);
  assert.match(source, /- name:\s*Run Direct-Live Proof/);
  assert.match(source, /npm run verify:deploy:direct-live-proof -- -FrontendPublicUrl/);
  assert.match(source, /- name:\s*Publish Railway Deploy Mode Summary/);
  assert.match(source, /railway_deploy_mode=/);
  assert.match(source, /real_deploy/);
  assert.match(source, /verify_only_fallback/);
  assert.match(source, /deploy_failed_no_fallback/);
  assert.match(source, /- name:\s*Publish Railway Deploy Provenance Summary/);
  assert.match(source, /artifacts\/deploy\/railway-deploy-summary\.json/);
  assert.match(source, /Railway deploy summary path:/);
  assert.match(source, /Railway deploy summary status:/);
  assert.match(source, /Railway deploy summary badge-details URL:/);
  assert.match(source, /Railway deploy summary was not generated\./);
  assert.match(source, /Production smoke status:/);
  assert.match(source, /Production smoke gateway runtime:/);
  assert.match(source, /Production smoke frontend health:/);
  assert.match(source, /Production smoke frontend title:/);
  assert.match(source, /Production smoke badge:/);
  assert.match(source, /Production smoke was not generated\./);
  assert.match(source, /Direct-live proof status:/);
  assert.match(source, /Direct-live proof API URL:/);
  assert.match(source, /Direct-live proof requested session:/);
  assert.match(source, /Direct-live proof transport:/);
  assert.match(source, /Direct-live proof latency:/);
  assert.match(source, /Direct-live proof fallback events:/);
  assert.match(source, /Direct-live proof runtime evidence expectation:/);
  assert.match(source, /Direct-live proof case-wiki signature expectation:/);
  assert.match(source, /Direct-live proof case-wiki signature observed:/);
  assert.match(source, /Direct-live proof was not generated\./);
  assert.match(source, /- name:\s*Upload Railway Deploy Artifacts/);
  assert.match(source, /name:\s*railway-deploy-all-artifacts/);
  assert.match(source, /artifacts\/deploy\/production-smoke\.json/);
  assert.match(source, /artifacts\/deploy\/production-smoke\.md/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.json/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.md/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.png/);
  assert.match(source, /-SkipReleaseVerification/);
  assert.match(source, /-GatewayDemoFrontendPublicUrl/);
  assert.match(source, /-FrontendApiBaseUrl/);
  assert.match(source, /-FrontendWsUrl/);
  assert.match(source, /-GatewayRootDescriptorCheckMaxAttempts/);
  assert.match(source, /-GatewayRootDescriptorCheckRetryBackoffSec/);
  assert.match(source, /-SkipGatewayDeploy/);
  assert.match(source, /-SkipFrontendDeploy/);
  assert.match(source, /-GatewaySkipRootDescriptorCheck/);
  assert.match(source, /-GatewayNoWait/);
  assert.match(source, /-FrontendNoWait/);
  assert.match(source, /-FrontendSkipHealthCheck/);
});

test("readme documents deploy-all workflow and required secrets", () => {
  const readmePath = resolve(process.cwd(), "README.md");
  const readme = readFileSync(readmePath, "utf8");

  assert.match(readme, /railway-deploy-all\.yml/);
  assert.match(readme, /RAILWAY_API_TOKEN/);
  assert.match(readme, /RAILWAY_TOKEN/);
  assert.match(readme, /RAILWAY_PROJECT_TOKEN/);
  assert.match(readme, /RAILWAY_PROJECT_ID/);
  assert.match(readme, /RAILWAY_SERVICE_ID/);
  assert.match(readme, /artifacts\/deploy\/railway-deploy-summary\.json/);
  assert.match(readme, /artifacts\/deploy\/production-smoke\.json/);
  assert.match(readme, /railway-deploy-all-artifacts/);
  assert.match(readme, /frontend_api_base_url/);
  assert.match(readme, /frontend_ws_url/);
});

test("railway deploy-all workflow installs playwright before combined deploy", () => {
  const workflowPath = resolve(process.cwd(), ".github", "workflows", "railway-deploy-all.yml");
  const source = readFileSync(workflowPath, "utf8");

  const installIndex = source.indexOf("- name: Install Playwright Browser");
  const deployIndex = source.indexOf("- name: Run Combined Railway Deploy");

  assert.notEqual(installIndex, -1);
  assert.notEqual(deployIndex, -1);
  assert.ok(installIndex < deployIndex);
});
