import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("release evidence report helper keeps required evidence lanes and outputs", () => {
  const scriptPath = resolve(process.cwd(), "scripts", "release-evidence-report.ps1");
  const source = readFileSync(scriptPath, "utf8");

  assert.match(source, /BadgeDetailsPath/);
  assert.match(source, /OutputJsonPath/);
  assert.match(source, /OutputMarkdownPath/);
  assert.match(source, /OutputManifestJsonPath/);
  assert.match(source, /OutputManifestMarkdownPath/);
  assert.match(source, /HostedDirectLiveProofMaxAgeHours/);
  assert.match(source, /artifacts\/release-evidence\/report\.json/);
  assert.match(source, /artifacts\/release-evidence\/report\.md/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.json/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.md/);
  assert.match(source, /turnTruncationStatus/);
  assert.match(source, /turnDeleteStatus/);
  assert.match(source, /operatorDamageControlStatus/);
  assert.match(source, /governancePolicyStatus/);
  assert.match(source, /skillsRegistryStatus/);
  assert.match(source, /pluginMarketplaceStatus/);
  assert.match(source, /deviceNodesStatus/);
  assert.match(source, /agentUsageStatus/);
  assert.match(source, /runtimeGuardrailsSignalPathsStatus/);
  assert.match(source, /liveTransportStatus/);
  assert.match(source, /hostedDirectLiveProofStatus/);
  assert.match(source, /caseWikiEvidenceSignatureStatus/);
  assert.match(source, /caseWikiRoutingContextStatus/);
  assert.match(source, /browserWorkerRecoveryStatus/);
  assert.match(source, /navigatorVisaFlowsStatus/);
  assert.match(source, /providerUsageStatus/);
  assert.match(source, /deviceNodeUpdatesStatus/);
  assert.match(source, /runtimeGuardrailsSignalPaths = \[ordered\]@/);
  assert.match(source, /liveTransport = \[ordered\]@/);
  assert.match(source, /hostedDirectLiveProof = \[ordered\]@/);
  assert.match(source, /caseWikiEvidenceSignature = \[ordered\]@/);
  assert.match(source, /caseWikiRoutingContext = \[ordered\]@/);
  assert.match(source, /navigatorVisaFlows = \[ordered\]@/);
  assert.match(source, /providerUsage = \[ordered\]@/);
  assert.match(source, /summaryStatus\s*=\s*"unavailable"/);
  assert.match(source, /totalPaths\s*=\s*0/);
  assert.match(source, /primaryPath\s*=\s*\$null/);
  assert.match(source, /activeSecondaryProviders/);
  assert.match(source, /entriesCount/);
  assert.match(source, /primaryEntry/);
  assert.match(source, /Convert-ToNonNegativeIntOrDefault/);
  assert.match(source, /New-RuntimeGuardrailsPrimaryPath/);
  assert.match(source, /New-LiveTransportSnapshot/);
  assert.match(source, /New-HostedDirectLiveProofFreshnessSnapshot/);
  assert.match(source, /New-HostedDirectLiveProofSnapshot/);
  assert.match(source, /New-CaseWikiEvidenceSignatureSnapshot/);
  assert.match(source, /New-HostedCaseWikiEvidenceSignatureValue/);
  assert.match(source, /Resolve-CaseWikiEvidenceSignatureSnapshot/);
  assert.match(source, /New-CaseWikiRoutingContextSnapshot/);
  assert.match(source, /New-BrowserWorkerRecoverySnapshot/);
  assert.match(source, /New-NavigatorVisaFlowsSnapshot/);
  assert.match(source, /New-ProviderUsagePrimaryEntry/);
  assert.match(source, /\$maxAttempts = 8/);
  assert.match(source, /\$baseRetryDelayMs = 80/);
  assert.match(source, /catch \[System\.IO\.IOException\]/);
  assert.match(source, /Start-Sleep -Milliseconds \(\$baseRetryDelayMs \* \$attempt\)/);
  assert.match(source, /updatesValidated/);
  assert.match(source, /updatesHasUpsert/);
  assert.match(source, /updatesHasHeartbeat/);
  assert.match(source, /updatesApiValidated/);
  assert.match(source, /updatesTotal/);
  assert.match(source, /criticalEvidenceStatuses/);
  assert.match(source, /runtimeGuardrailsSignalPaths/);
  assert.match(source, /Runtime Guardrails Signal Paths Snapshot/);
  assert.match(source, /Live Transport Snapshot/);
  assert.match(source, /Hosted Direct-Live Proof Snapshot/);
  assert.match(source, /freshnessStatus/);
  assert.match(source, /freshnessSummary/);
  assert.match(source, /freshnessAgeMinutes/);
  assert.match(source, /freshnessMaxAgeHours/);
  assert.match(source, /runtimeEvidenceExpectedSignatureStatus/);
  assert.match(source, /runtimeEvidenceKeyState/);
  assert.match(source, /caseWikiExpectedSignatureStatus/);
  assert.match(source, /caseWikiExpectedSignatureSource/);
  assert.match(source, /Case Wiki Evidence Signature Snapshot/);
  assert.match(source, /Case Wiki Routing Context Snapshot/);
  assert.match(source, /Browser Worker Recovery Snapshot/);
  assert.match(source, /Navigator Visa Flows Snapshot/);
  assert.match(source, /Secondary Provider Usage/);
  assert.match(source, /Artifact Inventory/);
  assert.match(source, /GCP Submission Follow-Up/);
  assert.match(source, /Submission Assets/);
  assert.match(source, /Submission Refresh Gate/);
  assert.match(source, /New-ArtifactEntry/);
  assert.match(source, /release\.manifestJson/);
  assert.match(source, /release\.manifestMarkdown/);
  assert.match(source, /deploy\.directLiveProofJson/);
  assert.match(source, /deploy\.directLiveProofMarkdown/);
  assert.match(source, /deploy\.directLiveProofScreenshot/);
  assert.match(source, /demo\.navigatorVisaFlows/);
  assert.match(source, /artifactRevalidation\.sourceRunManifest/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.json/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.md/);
  assert.match(source, /artifacts\/deploy\/direct-live-proof\.png/);
  assert.match(source, /gcp-cloud-run-summary\.json/);
  assert.match(source, /gcp-firestore-summary\.json/);
  assert.match(source, /gcp-runtime-proof\.json/);
  assert.match(source, /submission-refresh-status\.json/);
  assert.match(source, /submission-refresh-status\.md/);
  assert.match(source, /video-shot-list\.md/);
  assert.match(source, /video-script-4min\.md/);
  assert.match(source, /screen-checklist\.md/);
  assert.match(source, /bonus-article-draft\.md/);
  assert.match(source, /submissionSafeSummaryGate/);
  assert.match(source, /submissionRefreshStatus/);
  assert.match(source, /\$report\.statuses\.deviceNodeUpdatesStatus = "pass"/);
  assert.match(source, /\$report\.statuses\.deviceNodeUpdatesStatus = "fail"/);
  assert.match(source, /\$report\.statuses\.liveTransportStatus = Get-StatusValueOrDefault/);
  assert.match(source, /\$report\.statuses\.hostedDirectLiveProofStatus = Get-StatusValueOrDefault/);
  assert.match(source, /\$report\.statuses\.caseWikiEvidenceSignatureStatus = Get-StatusValueOrDefault/);
  assert.match(source, /\$report\.statuses\.navigatorVisaFlowsStatus = Get-StatusValueOrDefault/);
  assert.match(source, /hosted_direct_live_proof/);
  assert.match(source, /badge_details/);
  assert.match(source, /\$report\.caseWikiEvidenceSignature = Resolve-CaseWikiEvidenceSignatureSnapshot/);
  assert.match(source, /\[release-evidence-report\] JSON:/);
  assert.match(source, /\[release-evidence-report\] Markdown:/);
  assert.match(source, /\[release-evidence-report\] Manifest JSON:/);
  assert.match(source, /\[release-evidence-report\] Manifest Markdown:/);
});
