import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("release evidence report helper keeps required evidence lanes and outputs", () => {
  const scriptPath = resolve(process.cwd(), "scripts", "release-evidence-report.ps1");
  const source = readFileSync(scriptPath, "utf8");

  assert.match(source, /BadgeDetailsPath/);
  assert.match(source, /OutputJsonPath/);
  assert.match(source, /OutputMarkdownPath/);
  assert.match(source, /OutputManifestJsonPath/);
  assert.match(source, /OutputManifestMarkdownPath/);
  assert.match(source, /artifacts\/release-evidence\/report\.json/);
  assert.match(source, /artifacts\/release-evidence\/report\.md/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.json/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.md/);
  assert.match(source, /turnTruncationStatus/);
  assert.match(source, /turnDeleteStatus/);
  assert.match(source, /operatorDamageControlStatus/);
  assert.match(source, /governancePolicyStatus/);
  assert.match(source, /skillsRegistryStatus/);
  assert.match(source, /pluginMarketplaceStatus/);
  assert.match(source, /deviceNodesStatus/);
  assert.match(source, /agentUsageStatus/);
  assert.match(source, /runtimeGuardrailsSignalPathsStatus/);
  assert.match(source, /providerUsageStatus/);
  assert.match(source, /deviceNodeUpdatesStatus/);
  assert.match(source, /runtimeGuardrailsSignalPaths = \[ordered\]@/);
  assert.match(source, /providerUsage = \[ordered\]@/);
  assert.match(source, /summaryStatus\s*=\s*"unavailable"/);
  assert.match(source, /totalPaths\s*=\s*0/);
  assert.match(source, /primaryPath\s*=\s*\$null/);
  assert.match(source, /activeSecondaryProviders/);
  assert.match(source, /entriesCount/);
  assert.match(source, /primaryEntry/);
  assert.match(source, /Convert-ToNonNegativeIntOrDefault/);
  assert.match(source, /New-RuntimeGuardrailsPrimaryPath/);
  assert.match(source, /New-ProviderUsagePrimaryEntry/);
  assert.match(source, /\$maxAttempts = 8/);
  assert.match(source, /\$baseRetryDelayMs = 80/);
  assert.match(source, /catch \[System\.IO\.IOException\]/);
  assert.match(source, /Start-Sleep -Milliseconds \(\$baseRetryDelayMs \* \$attempt\)/);
  assert.match(source, /updatesValidated/);
  assert.match(source, /updatesHasUpsert/);
  assert.match(source, /updatesHasHeartbeat/);
  assert.match(source, /updatesApiValidated/);
  assert.match(source, /updatesTotal/);
  assert.match(source, /criticalEvidenceStatuses/);
  assert.match(source, /runtimeGuardrailsSignalPaths/);
  assert.match(source, /Runtime Guardrails Signal Paths Snapshot/);
  assert.match(source, /Secondary Provider Usage/);
  assert.match(source, /Artifact Inventory/);
  assert.match(source, /GCP Submission Follow-Up/);
  assert.match(source, /Submission Assets/);
  assert.match(source, /Submission Refresh Gate/);
  assert.match(source, /New-ArtifactEntry/);
  assert.match(source, /release\.manifestJson/);
  assert.match(source, /release\.manifestMarkdown/);
  assert.match(source, /artifactRevalidation\.sourceRunManifest/);
  assert.match(source, /gcp-cloud-run-summary\.json/);
  assert.match(source, /gcp-firestore-summary\.json/);
  assert.match(source, /gcp-runtime-proof\.json/);
  assert.match(source, /submission-refresh-status\.json/);
  assert.match(source, /submission-refresh-status\.md/);
  assert.match(source, /video-shot-list\.md/);
  assert.match(source, /video-script-4min\.md/);
  assert.match(source, /screen-checklist\.md/);
  assert.match(source, /bonus-article-draft\.md/);
  assert.match(source, /submissionSafeSummaryGate/);
  assert.match(source, /submissionRefreshStatus/);
  assert.match(source, /\$report\.statuses\.deviceNodeUpdatesStatus = "pass"/);
  assert.match(source, /\$report\.statuses\.deviceNodeUpdatesStatus = "fail"/);
  assert.match(source, /\[release-evidence-report\] JSON:/);
  assert.match(source, /\[release-evidence-report\] Markdown:/);
  assert.match(source, /\[release-evidence-report\] Manifest JSON:/);
  assert.match(source, /\[release-evidence-report\] Manifest Markdown:/);
});
