import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("release artifact revalidation workflow resolves source artifacts and runs artifact-only gate", () => {
  const workflowPath = resolve(process.cwd(), ".github", "workflows", "release-artifact-revalidation.yml");
  const source = readFileSync(workflowPath, "utf8");

  assert.match(source, /name:\s*Release Artifact Revalidation/);
  assert.match(source, /workflow_dispatch:/);
  assert.match(source, /source_run_id:/);
  assert.match(source, /artifact_name:/);
  assert.match(source, /perf_gate_mode:/);
  assert.match(source, /strict_final_run:/);
  assert.match(source, /github_api_max_attempts:/);
  assert.match(source, /github_api_retry_backoff_ms:/);
  assert.match(source, /max_source_run_age_hours:/);
  assert.match(source, /allow_any_source_branch:/);
  assert.match(source, /default:\s*auto/);
  assert.match(source, /default:\s*false/);
  assert.match(source, /default:\s*"3"/);
  assert.match(source, /default:\s*"1200"/);
  assert.match(source, /default:\s*"168"/);
  assert.match(source, /-\s*with_perf/);
  assert.match(source, /-\s*without_perf/);
  assert.match(source, /actions\/github-script@v7/);
  assert.match(source, /demo-e2e\.yml/);
  assert.match(source, /release-strict-final\.yml/);
  assert.match(source, /getWorkflowRun/);
  assert.match(source, /withRetry/);
  assert.match(source, /artifact_id/);
  assert.match(source, /source_run_branch/);
  assert.match(source, /source_run_age_hours/);
  assert.match(source, /Invoke-WebRequest/);
  assert.match(source, /Get-ChildItem -Path "artifact-bundle" -Directory -Recurse -Filter "artifacts"/);
  assert.match(source, /Resolved nested artifacts directory:/);
  assert.match(source, /Using flat artifact root:/);
  assert.match(source, /id:\s*inspect_artifacts/);
  assert.match(source, /id:\s*write_manifest/);
  assert.match(source, /id:\s*release_evidence_report/);
  assert.match(source, /Build Release Evidence Report/);
  assert.match(source, /Write Source Run Manifest/);
  assert.match(source, /releaseEvidenceReportPresent/);
  assert.match(source, /railwayDeploySummaryPresent/);
  assert.match(source, /repoPublishSummaryPresent/);
  assert.match(source, /releaseEvidenceReport\.statuses\.turnTruncationStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.turnDeleteStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.operatorDamageControlStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.governancePolicyStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.skillsRegistryStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.pluginMarketplaceStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.deviceNodesStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.agentUsageStatus/);
  assert.match(source, /releaseEvidenceReport\.statuses\.runtimeGuardrailsSignalPathsStatus/);
  assert.match(source, /releaseEvidenceReport\.runtimeGuardrailsSignalPaths\.summaryStatus/);
  assert.match(source, /releaseEvidenceReport\.runtimeGuardrailsSignalPaths\.totalPaths/);
  assert.match(source, /releaseEvidenceReport\.runtimeGuardrailsSignalPaths\.primaryPath/);
  assert.match(source, /releaseEvidenceReport\.statuses\.providerUsageStatus/);
  assert.match(source, /releaseEvidenceReport\.providerUsage\.validated/);
  assert.match(source, /releaseEvidenceReport\.providerUsage\.activeSecondaryProviders/);
  assert.match(source, /releaseEvidenceReport\.providerUsage\.entriesCount/);
  assert.match(source, /releaseEvidenceReport\.providerUsage\.primaryEntry/);
  assert.match(source, /releaseEvidenceReport\.statuses\.deviceNodeUpdatesStatus/);
  assert.match(source, /railwayDeploySummary\.status/);
  assert.match(source, /railwayDeploySummary\.deploymentId/);
  assert.match(source, /railwayDeploySummary\.projectId/);
  assert.match(source, /railwayDeploySummary\.service/);
  assert.match(source, /railwayDeploySummary\.environment/);
  assert.match(source, /railwayDeploySummary\.effectiveStartCommand/);
  assert.match(source, /railwayDeploySummary\.configSource/);
  assert.match(source, /checks"\) -Name "rootDescriptor"/);
  assert.match(source, /railwayDeploySummaryRootDescriptorAttempted/);
  assert.match(source, /railwayDeploySummaryRootDescriptorSkipped/);
  assert.match(source, /railwayDeploySummaryRootDescriptorExpectedUiUrl/);
  assert.match(source, /railwayDeploySummaryPublicBadgeAttempted/);
  assert.match(source, /railwayDeploySummaryPublicBadgeSkipped/);
  assert.match(source, /railwayDeploySummary\.checks\.publicBadge\.badgeEndpoint/);
  assert.match(source, /railwayDeploySummary\.checks\.publicBadge\.badgeDetailsEndpoint/);
  assert.match(source, /repoPublishSummary\.branch/);
  assert.match(source, /repoPublishSummary\.remoteName/);
  assert.match(source, /repoPublishSummary\.verification\.script/);
  assert.match(source, /repoPublishSummaryVerificationSkipped/);
  assert.match(source, /repoPublishSummaryVerificationStrict/);
  assert.match(source, /repoPublishSummary\.verification\.releaseEvidenceArtifactsValidated/);
  assert.match(source, /repoPublishSummaryReleaseEvidenceArtifactsCount/);
  assert.match(source, /repoPublishSummaryCommitEnabled/);
  assert.match(source, /repoPublishSummaryPushEnabled/);
  assert.match(source, /repoPublishSummaryPagesEnabled/);
  assert.match(source, /repoPublishSummaryBadgeCheckEnabled/);
  assert.match(source, /repoPublishSummary\.steps\.railwayDeployEnabled/);
  assert.match(source, /repoPublishSummary\.steps\.railwayFrontendDeployEnabled/);
  assert.match(source, /repoPublishSummary\.runtime\.railwayPublicUrl/);
  assert.match(source, /repoPublishSummary\.runtime\.railwayDemoFrontendPublicUrl/);
  assert.match(source, /repoPublishSummaryRuntimeRailwayNoWait/);
  assert.match(source, /repoPublishSummaryRuntimeRailwayFrontendNoWait/);
  assert.match(source, /repoPublishSummary\.artifacts\.self/);
  assert.match(source, /repoPublishSummary\.artifacts\.railwayDeploySummary/);
  assert.match(source, /repoPublishSummary\.artifacts\.releaseEvidenceReportJson/);
  assert.match(source, /repoPublishSummary\.artifacts\.releaseEvidenceManifestJson/);
  assert.match(source, /repoPublishSummary\.artifacts\.badgeDetailsJson/);
  assert.match(source, /source-run\.json/);
  assert.match(source, /release-evidence\/report\.json/);
  assert.match(source, /release-evidence\/report\.md/);
  assert.match(source, /release-evidence-report\.ps1/);
  assert.match(source, /retryableStatusCodes/);
  assert.match(source, /has_perf_artifacts/);
  assert.match(source, /run_with_perf/);
  assert.match(source, /effective_perf_mode/);
  assert.match(source, /requested_perf_mode/);
  assert.match(source, /strict_final_run/);
  assert.match(source, /turn_truncation_status/);
  assert.match(source, /turn_delete_status/);
  assert.match(source, /operator_damage_control_status/);
  assert.match(source, /governance_policy_status/);
  assert.match(source, /skills_registry_status/);
  assert.match(source, /plugin_marketplace_status/);
  assert.match(source, /device_nodes_status/);
  assert.match(source, /agent_usage_status/);
  assert.match(source, /runtime_guardrails_signal_paths_status/);
  assert.match(source, /runtime_guardrails_signal_paths_summary_status/);
  assert.match(source, /runtime_guardrails_signal_paths_total_paths/);
  assert.match(source, /runtime_guardrails_signal_paths_primary_path_title/);
  assert.match(source, /provider_usage_status/);
  assert.match(source, /provider_usage_validated/);
  assert.match(source, /provider_usage_active_secondary_providers/);
  assert.match(source, /provider_usage_entries_count/);
  assert.match(source, /provider_usage_primary_entry_label/);
  assert.match(source, /device_node_updates_status/);
  assert.match(source, /railway_deploy_summary_present/);
  assert.match(source, /railway_deploy_summary_status/);
  assert.match(source, /railway_deploy_summary_deployment_id/);
  assert.match(source, /railway_deploy_summary_public_url/);
  assert.match(source, /railway_deploy_summary_badge_endpoint/);
  assert.match(source, /railway_deploy_summary_badge_details_endpoint/);
  assert.match(source, /railway_deploy_summary_project_id/);
  assert.match(source, /railway_deploy_summary_service/);
  assert.match(source, /railway_deploy_summary_environment/);
  assert.match(source, /railway_deploy_summary_effective_start_command/);
  assert.match(source, /railway_deploy_summary_config_source/);
  assert.match(source, /railway_deploy_summary_root_descriptor_attempted/);
  assert.match(source, /railway_deploy_summary_root_descriptor_skipped/);
  assert.match(source, /railway_deploy_summary_expected_ui_url/);
  assert.match(source, /railway_deploy_summary_public_badge_attempted/);
  assert.match(source, /railway_deploy_summary_public_badge_skipped/);
  assert.match(source, /repo_publish_summary_present/);
  assert.match(source, /repo_publish_summary_branch/);
  assert.match(source, /repo_publish_summary_remote_name/);
  assert.match(source, /repo_publish_summary_verification_script/);
  assert.match(source, /repo_publish_summary_verification_skipped/);
  assert.match(source, /repo_publish_summary_verification_strict/);
  assert.match(source, /repo_publish_summary_release_evidence_validated/);
  assert.match(source, /repo_publish_summary_release_evidence_artifacts_count/);
  assert.match(source, /repo_publish_summary_commit_enabled/);
  assert.match(source, /repo_publish_summary_push_enabled/);
  assert.match(source, /repo_publish_summary_pages_enabled/);
  assert.match(source, /repo_publish_summary_badge_check_enabled/);
  assert.match(source, /repo_publish_summary_railway_deploy_enabled/);
  assert.match(source, /repo_publish_summary_railway_frontend_deploy_enabled/);
  assert.match(source, /repo_publish_summary_runtime_railway_public_url/);
  assert.match(source, /repo_publish_summary_runtime_railway_frontend_public_url/);
  assert.match(source, /repo_publish_summary_runtime_railway_no_wait/);
  assert.match(source, /repo_publish_summary_runtime_railway_frontend_no_wait/);
  assert.match(source, /repo_publish_summary_artifact_self/);
  assert.match(source, /repo_publish_summary_artifact_railway_deploy_summary/);
  assert.match(source, /repo_publish_summary_artifact_release_evidence_report_json/);
  assert.match(source, /repo_publish_summary_artifact_release_evidence_manifest_json/);
  assert.match(source, /repo_publish_summary_artifact_badge_details_json/);
  assert.match(source, /Turn-truncation status \(badge evidence\):/);
  assert.match(source, /Turn-delete status \(badge evidence\):/);
  assert.match(source, /Operator damage-control status \(badge evidence\):/);
  assert.match(source, /Governance policy status \(badge evidence\):/);
  assert.match(source, /Skills registry status \(badge evidence\):/);
  assert.match(source, /Plugin-marketplace status \(badge evidence\):/);
  assert.match(source, /Device-nodes status \(badge evidence\):/);
  assert.match(source, /Agent-usage status \(badge evidence\):/);
  assert.match(source, /Runtime-guardrails-signal-paths status \(badge evidence\):/);
  assert.match(source, /Runtime-guardrails-signal-paths summary status \(badge evidence\):/);
  assert.match(source, /Runtime-guardrails-signal-paths total paths \(badge evidence\):/);
  assert.match(source, /Runtime-guardrails-signal-paths primary path title \(badge evidence\):/);
  assert.match(source, /Provider-usage status \(badge evidence\):/);
  assert.match(source, /Provider-usage validated \(badge evidence\):/);
  assert.match(source, /Provider-usage active secondary providers \(badge evidence\):/);
  assert.match(source, /Provider-usage entries count \(badge evidence\):/);
  assert.match(source, /Provider-usage primary entry \(badge evidence\):/);
  assert.match(source, /Device-node-updates status \(badge evidence\):/);
  assert.match(source, /Railway deploy summary present:/);
  assert.match(source, /Railway deploy summary status:/);
  assert.match(source, /Railway deploy summary deployment id:/);
  assert.match(source, /Railway deploy summary public URL:/);
  assert.match(source, /Railway deploy summary badge endpoint:/);
  assert.match(source, /Railway deploy summary badge-details endpoint:/);
  assert.match(source, /Railway deploy summary project id:/);
  assert.match(source, /Railway deploy summary service:/);
  assert.match(source, /Railway deploy summary environment:/);
  assert.match(source, /Railway deploy summary effective start command:/);
  assert.match(source, /Railway deploy summary config source:/);
  assert.match(source, /Railway deploy summary root-descriptor attempted:/);
  assert.match(source, /Railway deploy summary root-descriptor skipped:/);
  assert.match(source, /Railway deploy summary expected UI URL:/);
  assert.match(source, /Railway deploy summary public-badge attempted:/);
  assert.match(source, /Railway deploy summary public-badge skipped:/);
  assert.match(source, /Repo publish summary present:/);
  assert.match(source, /Repo publish summary branch:/);
  assert.match(source, /Repo publish summary remote name:/);
  assert.match(source, /Repo publish summary verification script:/);
  assert.match(source, /Repo publish summary verification skipped:/);
  assert.match(source, /Repo publish summary verification strict:/);
  assert.match(source, /Repo publish summary release-evidence validated:/);
  assert.match(source, /Repo publish summary release-evidence artifacts count:/);
  assert.match(source, /Repo publish summary commit enabled:/);
  assert.match(source, /Repo publish summary push enabled:/);
  assert.match(source, /Repo publish summary pages enabled:/);
  assert.match(source, /Repo publish summary badge-check enabled:/);
  assert.match(source, /Repo publish summary Railway deploy enabled:/);
  assert.match(source, /Repo publish summary Railway frontend deploy enabled:/);
  assert.match(source, /Repo publish summary runtime Railway public URL:/);
  assert.match(source, /Repo publish summary runtime Railway frontend URL:/);
  assert.match(source, /Repo publish summary runtime Railway no-wait:/);
  assert.match(source, /Repo publish summary runtime Railway frontend no-wait:/);
  assert.match(source, /Repo publish summary artifact self:/);
  assert.match(source, /Repo publish summary artifact Railway deploy summary:/);
  assert.match(source, /Repo publish summary artifact release-evidence report JSON:/);
  assert.match(source, /Repo publish summary artifact release-evidence manifest JSON:/);
  assert.match(source, /Repo publish summary artifact badge-details JSON:/);
  assert.match(source, /Release evidence report JSON:/);
  assert.match(source, /Release evidence report Markdown:/);
  assert.match(source, /GitHub API retry attempts/);
  assert.match(source, /GitHub API retry backoff ms/);
  assert.match(source, /Source run workflow:/);
  assert.match(source, /Source run branch:/);
  assert.match(source, /Source run head sha:/);
  assert.match(source, /Source run updated at:/);
  assert.match(source, /Source run age hours:/);
  assert.match(source, /Allow any source branch:/);
  assert.match(source, /Max source run age hours:/);
  assert.match(source, /Source run manifest:/);
  assert.match(source, /npm run verify:release:artifact-only/);
  assert.match(source, /-SkipPerfLoad/);
  assert.match(source, /-StrictFinalRun/);

  const buildEvidenceIndex = source.indexOf("- name: Build Release Evidence Report");
  const writeManifestIndex = source.indexOf("- name: Write Source Run Manifest");
  assert.notEqual(buildEvidenceIndex, -1);
  assert.notEqual(writeManifestIndex, -1);
  assert.ok(
    buildEvidenceIndex < writeManifestIndex,
    "Build Release Evidence Report must run before Write Source Run Manifest"
  );
});

test("release artifact revalidation workflow publishes consolidated artifacts", () => {
  const workflowPath = resolve(process.cwd(), ".github", "workflows", "release-artifact-revalidation.yml");
  const source = readFileSync(workflowPath, "utf8");

  assert.match(source, /name:\s*release-artifact-revalidation-artifacts/);
  assert.match(source, /artifacts\/demo-e2e\/summary\.json/);
  assert.match(source, /artifacts\/demo-e2e\/policy-check\.json/);
  assert.match(source, /artifacts\/perf-load\/summary\.json/);
  assert.match(source, /artifacts\/perf-load\/policy-check\.json/);
  assert.match(source, /artifacts\/release-evidence\/report\.json/);
  assert.match(source, /artifacts\/release-evidence\/report\.md/);
  assert.match(source, /artifacts\/deploy\/railway-deploy-summary\.json/);
  assert.match(source, /artifacts\/deploy\/repo-publish-summary\.json/);
  assert.match(source, /artifacts\/release-artifact-revalidation\/source-run\.json/);
});

test("workflow docs include retry-control inputs", () => {
  const readmePath = resolve(process.cwd(), "README.md");
  const runbookPath = resolve(process.cwd(), "docs", "challenge-demo-runbook.md");
  const readme = readFileSync(readmePath, "utf8");
  const runbook = readFileSync(runbookPath, "utf8");

  for (const content of [readme, runbook]) {
    assert.match(content, /release-artifact-revalidation/);
    assert.match(content, /github_api_max_attempts/);
    assert.match(content, /github_api_retry_backoff_ms/);
    assert.match(content, /max_source_run_age_hours/);
    assert.match(content, /allow_any_source_branch/);
    assert.match(content, /artifacts\/release-evidence\/report\.json/);
    assert.match(content, /artifacts\/release-evidence\/report\.md/);
  }
});

