import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("repo publish script includes pre-publish release verification controls", () => {
  const scriptPath = resolve(process.cwd(), "scripts", "github-repo-publish.ps1");
  const source = readFileSync(scriptPath, "utf8");

  assert.match(source, /\[switch\]\$SkipReleaseVerification/);
  assert.match(source, /\[switch\]\$StrictReleaseVerification/);
  assert.match(source, /npm run \$verificationScript/);
  assert.match(source, /function Resolve-NpmCli\(\)/);
  assert.match(source, /\$npmCli = Resolve-NpmCli/);
  assert.match(source, /& \$npmCli run \$verificationScript/);
  assert.match(source, /verify:release:strict/);
  assert.match(source, /verify:release/);
  assert.match(source, /\[switch\]\$DeployRailway/);
  assert.match(source, /\[string\]\$RailwayProjectId = \$env:RAILWAY_PROJECT_ID/);
  assert.match(source, /\[string\]\$RailwayServiceId = \$env:RAILWAY_SERVICE_ID/);
  assert.match(source, /\[switch\]\$RailwaySkipPublicBadgeCheck/);
  assert.match(source, /\[switch\]\$RailwaySkipRootDescriptorCheck/);
  assert.match(source, /\[string\]\$RailwayPublicBadgeEndpoint = \$env:PUBLIC_BADGE_ENDPOINT/);
  assert.match(source, /\[string\]\$RailwayPublicBadgeDetailsEndpoint = \$env:PUBLIC_BADGE_DETAILS_ENDPOINT/);
  assert.match(source, /\[string\]\$RailwayPublicUrl = \$env:RAILWAY_PUBLIC_URL/);
  assert.match(source, /\[string\]\$RailwayDemoFrontendPublicUrl = \$env:DEMO_FRONTEND_PUBLIC_URL/);
  assert.match(source, /\[int\]\$RailwayPublicBadgeCheckTimeoutSec = 20/);
  assert.match(source, /\[int\]\$RailwayRootDescriptorCheckMaxAttempts = 3/);
  assert.match(source, /\[int\]\$RailwayRootDescriptorCheckRetryBackoffSec = 2/);
  assert.match(source, /\[switch\]\$DeployRailwayFrontend/);
  assert.match(source, /\[string\]\$RailwayFrontendService = \$\(/);
  assert.match(source, /\[string\]\$RailwayFrontendPath = "apps\/demo-frontend"/);
  assert.match(source, /\[string\]\$RailwayFrontendWsUrl = \$env:FRONTEND_WS_URL/);
  assert.match(source, /\[string\]\$RailwayFrontendApiBaseUrl = \$env:FRONTEND_API_BASE_URL/);
  assert.match(source, /\[switch\]\$RailwayFrontendNoWait/);
  assert.match(source, /\[switch\]\$RailwayFrontendSkipHealthCheck/);
  assert.match(source, /\[int\]\$RailwayFrontendHealthCheckTimeoutSec = 20/);
  assert.match(source, /function Run-Git\(\[string\[\]\]\$CliArgs\)/);
  assert.doesNotMatch(source, /function Run-Git\(\[string\[\]\]\$Args\)/);
  assert.match(source, /function Normalize-GitHubRemote\(\[string\]\$Url\)/);
  assert.match(source, /function Convert-ToWebSocketBaseUrl\(\[string\]\$HttpBaseUrl\)/);
  assert.match(source, /\$existingRemoteCanonical = Normalize-GitHubRemote/);
  assert.match(source, /\$targetRemoteCanonical = Normalize-GitHubRemote/);
  assert.match(source, /Using existing equivalent URL/);
  assert.match(source, /railway-deploy\.ps1/);
  assert.match(source, /railway-deploy-frontend\.ps1/);
  assert.match(source, /\-SkipReleaseVerification/);
  assert.match(source, /\-SkipPublicBadgeCheck/);
  assert.match(source, /\-SkipRootDescriptorCheck/);
  assert.match(source, /\-PublicBadgeEndpoint/);
  assert.match(source, /\-PublicBadgeDetailsEndpoint/);
  assert.match(source, /\-RailwayPublicUrl/);
  assert.match(source, /\-DemoFrontendPublicUrl/);
  assert.match(source, /\-PublicBadgeCheckTimeoutSec/);
  assert.match(source, /\-RootDescriptorCheckMaxAttempts/);
  assert.match(source, /\-RootDescriptorCheckRetryBackoffSec/);
  assert.match(source, /if \(\$DeployRailway -and \$RailwayRootDescriptorCheckMaxAttempts -lt 1\)\s*\{[\s\S]*RailwayRootDescriptorCheckMaxAttempts must be >= 1/);
  assert.match(source, /if \(\$DeployRailway -and \$RailwayRootDescriptorCheckRetryBackoffSec -lt 0\)\s*\{[\s\S]*RailwayRootDescriptorCheckRetryBackoffSec must be >= 0/);

  const readmePath = resolve(process.cwd(), "README.md");
  const readme = readFileSync(readmePath, "utf8");
  assert.match(readme, /\-RailwayRootDescriptorCheckMaxAttempts <n>/);
  assert.match(readme, /\-RailwayRootDescriptorCheckRetryBackoffSec <n>/);
});
