import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

test("repo publish script includes pre-publish release verification controls", () => {
  const scriptPath = resolve(process.cwd(), "scripts", "github-repo-publish.ps1");
  const source = readFileSync(scriptPath, "utf8");

  assert.match(source, /\[switch\]\$SkipReleaseVerification/);
  assert.match(source, /\[switch\]\$StrictReleaseVerification/);
  assert.match(source, /npm run \$verificationScript/);
  assert.match(source, /function Resolve-NpmCli\(\)/);
  assert.match(source, /\$npmCli = Resolve-NpmCli/);
  assert.match(source, /& \$npmCli run \$verificationScript/);
  assert.match(source, /verify:release:strict/);
  assert.match(source, /verify:release/);
  assert.match(source, /function Assert-ReleaseEvidenceArtifactsPresent\(\)/);
  assert.match(source, /artifacts\/release-evidence\/report\.json/);
  assert.match(source, /artifacts\/release-evidence\/report\.md/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.json/);
  assert.match(source, /artifacts\/release-evidence\/manifest\.md/);
  assert.match(source, /artifacts\/demo-e2e\/badge-details\.json/);
  assert.match(source, /function Write-Utf8NoBomFile\(/);
  assert.match(source, /function Write-RepoPublishSummary\(/);
  assert.match(source, /function Write-GitHubOutputValue\(/);
  assert.match(source, /function Write-GitHubStepSummaryLine\(/);
  assert.match(source, /function Read-JsonArtifactIfPresent\(/);
  assert.match(source, /function Get-CompactRuntimeGuardrailsPrimaryPath\(/);
  assert.match(source, /function Get-CompactProviderUsagePrimaryEntry\(/);
  assert.match(source, /function Get-ReleaseEvidenceSnapshot\(\[bool\]\$ValidatedInThisRun\)/);
  assert.match(source, /\$env:GITHUB_OUTPUT/);
  assert.match(source, /\$env:GITHUB_STEP_SUMMARY/);
  assert.match(source, /artifacts\\deploy\\repo-publish-summary\.json/);
  assert.match(source, /repo_publish_summary_path/);
  assert.match(source, /repo_publish_verification_script/);
  assert.match(source, /repo_publish_verification_skipped/);
  assert.match(source, /repo_publish_verification_strict/);
  assert.match(source, /repo_publish_release_evidence_validated/);
  assert.match(source, /repo_publish_release_evidence_artifacts_count/);
  assert.match(source, /repo_publish_railway_deploy_enabled/);
  assert.match(source, /repo_publish_railway_frontend_deploy_enabled/);
  assert.match(source, /repo_publish_railway_summary_path/);
  assert.match(source, /repo_publish_release_evidence_snapshot_available/);
  assert.match(source, /repo_publish_release_evidence_missing_required/);
  assert.match(source, /repo_publish_release_evidence_badge_checks/);
  assert.match(source, /repo_publish_release_evidence_runtime_guardrails_summary_status/);
  assert.match(source, /repo_publish_release_evidence_report_path/);
  assert.match(source, /repo_publish_release_evidence_manifest_path/);
  assert.match(source, /repo_publish_badge_details_path/);
  assert.match(source, /Repo publish summary artifact:/);
  assert.match(source, /Repo publish verification script:/);
  assert.match(source, /Repo publish verification skipped:/);
  assert.match(source, /Repo publish verification strict:/);
  assert.match(source, /Repo publish release-evidence artifacts count:/);
  assert.match(source, /Repo publish release-evidence snapshot available:/);
  assert.match(source, /Repo publish release-evidence missing required artifacts:/);
  assert.match(source, /Repo publish release-evidence badge checks:/);
  assert.match(source, /Repo publish release-evidence runtime guardrails:/);
  assert.match(source, /Repo publish release-evidence report artifact:/);
  assert.match(source, /Repo publish release-evidence manifest artifact:/);
  assert.match(source, /Repo publish badge-details artifact:/);
  assert.match(source, /Summary artifact:/);
  assert.match(source, /Pre-publish release evidence artifacts are missing:/);
  assert.match(source, /Release evidence artifacts:/);
  assert.match(source, /\$releaseEvidenceSnapshot = Get-ReleaseEvidenceSnapshot -ValidatedInThisRun \(-not \$SkipReleaseVerification\)/);
  assert.match(source, /releaseEvidenceSnapshot = \$releaseEvidenceSnapshot/);
  assert.match(source, /available = \(\(\$null -ne \$report\) -or \(\$null -ne \$manifest\) -or \(\$null -ne \$badgeDetails\)\)/);
  assert.match(source, /validatedInThisRun = \$ValidatedInThisRun/);
  assert.match(source, /releaseEvidenceArtifactsCount = @\(if \(\$releaseEvidenceArtifacts.Count -gt 0\) \{ \$releaseEvidenceArtifacts \} else \{ Get-RequiredReleaseEvidenceArtifacts \}\)\.Count/);
  assert.match(source, /releaseEvidenceReportJson = "artifacts\/release-evidence\/report\.json"/);
  assert.match(source, /releaseEvidenceManifestJson = "artifacts\/release-evidence\/manifest\.json"/);
  assert.match(source, /badgeDetailsJson = "artifacts\/demo-e2e\/badge-details\.json"/);
  assert.match(source, /manifestInventory = if \(\$null -ne \$manifest -and \$null -ne \$manifest\.inventory\)/);
  assert.match(source, /criticalEvidenceStatuses = \$criticalEvidenceStatuses/);
  assert.match(source, /deviceNodeUpdates = if \(\$null -ne \$deviceNodeUpdatesSource\)/);
  assert.match(source, /runtimeGuardrails = if \(\$null -ne \$runtimeGuardrailsSource\)/);
  assert.match(source, /providerUsage = if \(\$null -ne \$providerUsageSource\)/);
  assert.match(source, /badgeDetails = if \(\$null -ne \$badgeDetails\)/);
  assert.match(source, /\[switch\]\$DeployRailway/);
  assert.match(source, /\[string\]\$RailwayProjectId = \$env:RAILWAY_PROJECT_ID/);
  assert.match(source, /\[string\]\$RailwayServiceId = \$env:RAILWAY_SERVICE_ID/);
  assert.match(source, /\[switch\]\$RailwaySkipPublicBadgeCheck/);
  assert.match(source, /\[switch\]\$RailwaySkipRootDescriptorCheck/);
  assert.match(source, /\[string\]\$RailwayPublicBadgeEndpoint = \$env:PUBLIC_BADGE_ENDPOINT/);
  assert.match(source, /\[string\]\$RailwayPublicBadgeDetailsEndpoint = \$env:PUBLIC_BADGE_DETAILS_ENDPOINT/);
  assert.match(source, /\[string\]\$RailwayPublicUrl = \$env:RAILWAY_PUBLIC_URL/);
  assert.match(source, /\[string\]\$RailwayDemoFrontendPublicUrl = \$env:DEMO_FRONTEND_PUBLIC_URL/);
  assert.match(source, /\[int\]\$RailwayPublicBadgeCheckTimeoutSec = 20/);
  assert.match(source, /\[int\]\$RailwayRootDescriptorCheckMaxAttempts = 3/);
  assert.match(source, /\[int\]\$RailwayRootDescriptorCheckRetryBackoffSec = 2/);
  assert.match(source, /\[switch\]\$DeployRailwayFrontend/);
  assert.match(source, /\[string\]\$RailwayFrontendService = \$\(/);
  assert.match(source, /\[string\]\$RailwayFrontendPath = "apps\/demo-frontend"/);
  assert.match(source, /\[string\]\$RailwayFrontendWsUrl = \$env:FRONTEND_WS_URL/);
  assert.match(source, /\[string\]\$RailwayFrontendApiBaseUrl = \$env:FRONTEND_API_BASE_URL/);
  assert.match(source, /\[switch\]\$RailwayFrontendNoWait/);
  assert.match(source, /\[switch\]\$RailwayFrontendSkipHealthCheck/);
  assert.match(source, /\[int\]\$RailwayFrontendHealthCheckTimeoutSec = 20/);
  assert.match(source, /function Run-Git\(\[string\[\]\]\$CliArgs\)/);
  assert.doesNotMatch(source, /function Run-Git\(\[string\[\]\]\$Args\)/);
  assert.match(source, /function Normalize-GitHubRemote\(\[string\]\$Url\)/);
  assert.match(source, /function Convert-ToWebSocketBaseUrl\(\[string\]\$HttpBaseUrl\)/);
  assert.match(source, /\$existingRemoteCanonical = Normalize-GitHubRemote/);
  assert.match(source, /\$targetRemoteCanonical = Normalize-GitHubRemote/);
  assert.match(source, /Using existing equivalent URL/);
  assert.match(source, /railway-deploy\.ps1/);
  assert.match(source, /railway-deploy-frontend\.ps1/);
  assert.match(source, /\-SkipReleaseVerification/);
  assert.match(source, /\-SkipPublicBadgeCheck/);
  assert.match(source, /\-SkipRootDescriptorCheck/);
  assert.match(source, /\-PublicBadgeEndpoint/);
  assert.match(source, /\-PublicBadgeDetailsEndpoint/);
  assert.match(source, /\-RailwayPublicUrl/);
  assert.match(source, /\-DemoFrontendPublicUrl/);
  assert.match(source, /\-PublicBadgeCheckTimeoutSec/);
  assert.match(source, /\-RootDescriptorCheckMaxAttempts/);
  assert.match(source, /\-RootDescriptorCheckRetryBackoffSec/);
  assert.match(source, /if \(\$DeployRailway -and \$RailwayRootDescriptorCheckMaxAttempts -lt 1\)\s*\{[\s\S]*RailwayRootDescriptorCheckMaxAttempts must be >= 1/);
  assert.match(source, /if \(\$DeployRailway -and \$RailwayRootDescriptorCheckRetryBackoffSec -lt 0\)\s*\{[\s\S]*RailwayRootDescriptorCheckRetryBackoffSec must be >= 0/);

  const readmePath = resolve(process.cwd(), "README.md");
  const readme = readFileSync(readmePath, "utf8");
  assert.match(readme, /\-RailwayRootDescriptorCheckMaxAttempts <n>/);
  assert.match(readme, /\-RailwayRootDescriptorCheckRetryBackoffSec <n>/);
  assert.match(readme, /repo publish surfaces local release-evidence report\/manifest paths after pre-publish verification/);
  assert.match(readme, /artifacts\/deploy\/repo-publish-summary\.json/);
  assert.match(readme, /repo_publish_summary_path/);
  assert.match(readme, /GITHUB_OUTPUT/);
  assert.match(readme, /GITHUB_STEP_SUMMARY/);
});
